/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database;


import com.pereira.manolos.datos.database.tables.BitacoraCaja;
import com.pereira.manolos.datos.database.tables.Caja;
import com.pereira.manolos.datos.database.tables.CategoriaProducto;
import com.pereira.manolos.datos.database.tables.Cliente;
import com.pereira.manolos.datos.database.tables.ClienteCreditofiscal;
import com.pereira.manolos.datos.database.tables.Compra;
import com.pereira.manolos.datos.database.tables.CostosIndirectos;
import com.pereira.manolos.datos.database.tables.Cotizacion;
import com.pereira.manolos.datos.database.tables.DetalleCompra;
import com.pereira.manolos.datos.database.tables.DetalleCotizacion;
import com.pereira.manolos.datos.database.tables.DetallePromocion;
import com.pereira.manolos.datos.database.tables.DetalleReceta;
import com.pereira.manolos.datos.database.tables.DetalleVenta;
import com.pereira.manolos.datos.database.tables.Empleado;
import com.pereira.manolos.datos.database.tables.Empresa;
import com.pereira.manolos.datos.database.tables.Insumo;
import com.pereira.manolos.datos.database.tables.Medida;
import com.pereira.manolos.datos.database.tables.Modulo;
import com.pereira.manolos.datos.database.tables.PagosCompra;
import com.pereira.manolos.datos.database.tables.Permisos;
import com.pereira.manolos.datos.database.tables.Producto;
import com.pereira.manolos.datos.database.tables.Promocion;
import com.pereira.manolos.datos.database.tables.Proveedor;
import com.pereira.manolos.datos.database.tables.Puesto;
import com.pereira.manolos.datos.database.tables.Receta;
import com.pereira.manolos.datos.database.tables.Resolucion;
import com.pereira.manolos.datos.database.tables.UnidadMedida;
import com.pereira.manolos.datos.database.tables.Usuario;
import com.pereira.manolos.datos.database.tables.Venta;
import com.pereira.manolos.datos.database.tables.records.BitacoraCajaRecord;
import com.pereira.manolos.datos.database.tables.records.CajaRecord;
import com.pereira.manolos.datos.database.tables.records.CategoriaProductoRecord;
import com.pereira.manolos.datos.database.tables.records.ClienteCreditofiscalRecord;
import com.pereira.manolos.datos.database.tables.records.ClienteRecord;
import com.pereira.manolos.datos.database.tables.records.CompraRecord;
import com.pereira.manolos.datos.database.tables.records.CostosIndirectosRecord;
import com.pereira.manolos.datos.database.tables.records.CotizacionRecord;
import com.pereira.manolos.datos.database.tables.records.DetalleCompraRecord;
import com.pereira.manolos.datos.database.tables.records.DetalleCotizacionRecord;
import com.pereira.manolos.datos.database.tables.records.DetallePromocionRecord;
import com.pereira.manolos.datos.database.tables.records.DetalleRecetaRecord;
import com.pereira.manolos.datos.database.tables.records.DetalleVentaRecord;
import com.pereira.manolos.datos.database.tables.records.EmpleadoRecord;
import com.pereira.manolos.datos.database.tables.records.EmpresaRecord;
import com.pereira.manolos.datos.database.tables.records.InsumoRecord;
import com.pereira.manolos.datos.database.tables.records.MedidaRecord;
import com.pereira.manolos.datos.database.tables.records.ModuloRecord;
import com.pereira.manolos.datos.database.tables.records.PagosCompraRecord;
import com.pereira.manolos.datos.database.tables.records.PermisosRecord;
import com.pereira.manolos.datos.database.tables.records.ProductoRecord;
import com.pereira.manolos.datos.database.tables.records.PromocionRecord;
import com.pereira.manolos.datos.database.tables.records.ProveedorRecord;
import com.pereira.manolos.datos.database.tables.records.PuestoRecord;
import com.pereira.manolos.datos.database.tables.records.RecetaRecord;
import com.pereira.manolos.datos.database.tables.records.ResolucionRecord;
import com.pereira.manolos.datos.database.tables.records.UnidadMedidaRecord;
import com.pereira.manolos.datos.database.tables.records.UsuarioRecord;
import com.pereira.manolos.datos.database.tables.records.VentaRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CajaRecord, Integer> IDENTITY_CAJA = Identities0.IDENTITY_CAJA;
    public static final Identity<CategoriaProductoRecord, Integer> IDENTITY_CATEGORIA_PRODUCTO = Identities0.IDENTITY_CATEGORIA_PRODUCTO;
    public static final Identity<ClienteRecord, Integer> IDENTITY_CLIENTE = Identities0.IDENTITY_CLIENTE;
    public static final Identity<CompraRecord, Integer> IDENTITY_COMPRA = Identities0.IDENTITY_COMPRA;
    public static final Identity<CostosIndirectosRecord, Integer> IDENTITY_COSTOS_INDIRECTOS = Identities0.IDENTITY_COSTOS_INDIRECTOS;
    public static final Identity<CotizacionRecord, Integer> IDENTITY_COTIZACION = Identities0.IDENTITY_COTIZACION;
    public static final Identity<EmpleadoRecord, Integer> IDENTITY_EMPLEADO = Identities0.IDENTITY_EMPLEADO;
    public static final Identity<InsumoRecord, Integer> IDENTITY_INSUMO = Identities0.IDENTITY_INSUMO;
    public static final Identity<ModuloRecord, Integer> IDENTITY_MODULO = Identities0.IDENTITY_MODULO;
    public static final Identity<ProductoRecord, Integer> IDENTITY_PRODUCTO = Identities0.IDENTITY_PRODUCTO;
    public static final Identity<PromocionRecord, Integer> IDENTITY_PROMOCION = Identities0.IDENTITY_PROMOCION;
    public static final Identity<ProveedorRecord, Integer> IDENTITY_PROVEEDOR = Identities0.IDENTITY_PROVEEDOR;
    public static final Identity<PuestoRecord, Integer> IDENTITY_PUESTO = Identities0.IDENTITY_PUESTO;
    public static final Identity<RecetaRecord, Integer> IDENTITY_RECETA = Identities0.IDENTITY_RECETA;
    public static final Identity<ResolucionRecord, Integer> IDENTITY_RESOLUCION = Identities0.IDENTITY_RESOLUCION;
    public static final Identity<VentaRecord, Integer> IDENTITY_VENTA = Identities0.IDENTITY_VENTA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CajaRecord> CAJA_PKEY = UniqueKeys0.CAJA_PKEY;
    public static final UniqueKey<CategoriaProductoRecord> CATEGORIA_PRODUCTO_PKEY = UniqueKeys0.CATEGORIA_PRODUCTO_PKEY;
    public static final UniqueKey<ClienteRecord> PK_CLIENTE = UniqueKeys0.PK_CLIENTE;
    public static final UniqueKey<CompraRecord> COMPRA_PKEY = UniqueKeys0.COMPRA_PKEY;
    public static final UniqueKey<CostosIndirectosRecord> COSTOS_INDIRECTOS_PKEY = UniqueKeys0.COSTOS_INDIRECTOS_PKEY;
    public static final UniqueKey<CotizacionRecord> PK_COTIZACION = UniqueKeys0.PK_COTIZACION;
    public static final UniqueKey<EmpleadoRecord> PK_EMPLEADO = UniqueKeys0.PK_EMPLEADO;
    public static final UniqueKey<EmpresaRecord> PK_EMPRESA = UniqueKeys0.PK_EMPRESA;
    public static final UniqueKey<InsumoRecord> INSUMO_PKEY = UniqueKeys0.INSUMO_PKEY;
    public static final UniqueKey<MedidaRecord> PK_MEDIDA = UniqueKeys0.PK_MEDIDA;
    public static final UniqueKey<ModuloRecord> PK_ROL = UniqueKeys0.PK_ROL;
    public static final UniqueKey<ProductoRecord> PRODUCTO_PKEY = UniqueKeys0.PRODUCTO_PKEY;
    public static final UniqueKey<PromocionRecord> PROMOCION_PKEY = UniqueKeys0.PROMOCION_PKEY;
    public static final UniqueKey<ProveedorRecord> PROVEEDOR_PKEY = UniqueKeys0.PROVEEDOR_PKEY;
    public static final UniqueKey<PuestoRecord> PUESTO_PKEY = UniqueKeys0.PUESTO_PKEY;
    public static final UniqueKey<RecetaRecord> RECETA_PKEY = UniqueKeys0.RECETA_PKEY;
    public static final UniqueKey<ResolucionRecord> RESOLUCION_PKEY = UniqueKeys0.RESOLUCION_PKEY;
    public static final UniqueKey<UnidadMedidaRecord> PK_UNIDADMEDIDA = UniqueKeys0.PK_UNIDADMEDIDA;
    public static final UniqueKey<VentaRecord> PK_VENTA = UniqueKeys0.PK_VENTA;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BitacoraCajaRecord, CajaRecord> BITACORA_CAJA__FK_BITACORA_CAJA = ForeignKeys0.BITACORA_CAJA__FK_BITACORA_CAJA;
    public static final ForeignKey<ClienteCreditofiscalRecord, ClienteRecord> CLIENTE_CREDITOFISCAL__FK_CLIENTE_CREDITOFISCAL_CLIENTE_1 = ForeignKeys0.CLIENTE_CREDITOFISCAL__FK_CLIENTE_CREDITOFISCAL_CLIENTE_1;
    public static final ForeignKey<CompraRecord, ProveedorRecord> COMPRA__FK_COMPRA_PROVEEDOR_1 = ForeignKeys0.COMPRA__FK_COMPRA_PROVEEDOR_1;
    public static final ForeignKey<CotizacionRecord, ClienteRecord> COTIZACION__FK_COTIZACION_CLIENTE_1 = ForeignKeys0.COTIZACION__FK_COTIZACION_CLIENTE_1;
    public static final ForeignKey<DetalleCompraRecord, CompraRecord> DETALLE_COMPRA__FK_DETALLE_COMPRA_COMPRA_1 = ForeignKeys0.DETALLE_COMPRA__FK_DETALLE_COMPRA_COMPRA_1;
    public static final ForeignKey<DetalleCompraRecord, InsumoRecord> DETALLE_COMPRA__FK_DETALLE_COMPRA_INSUMO_1 = ForeignKeys0.DETALLE_COMPRA__FK_DETALLE_COMPRA_INSUMO_1;
    public static final ForeignKey<DetalleCotizacionRecord, PromocionRecord> DETALLE_COTIZACION__FK_DETALLE_COTIZA_PROMO = ForeignKeys0.DETALLE_COTIZACION__FK_DETALLE_COTIZA_PROMO;
    public static final ForeignKey<DetalleCotizacionRecord, CotizacionRecord> DETALLE_COTIZACION__FK_DETALLE_COTIZACION_COTIZACION = ForeignKeys0.DETALLE_COTIZACION__FK_DETALLE_COTIZACION_COTIZACION;
    public static final ForeignKey<DetalleCotizacionRecord, ProductoRecord> DETALLE_COTIZACION__FK_DETALLE_COTIZACION_PRODUCTO_1 = ForeignKeys0.DETALLE_COTIZACION__FK_DETALLE_COTIZACION_PRODUCTO_1;
    public static final ForeignKey<DetallePromocionRecord, PromocionRecord> DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PROMOCION_1 = ForeignKeys0.DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PROMOCION_1;
    public static final ForeignKey<DetallePromocionRecord, ProductoRecord> DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PRODUCTO_1 = ForeignKeys0.DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PRODUCTO_1;
    public static final ForeignKey<DetalleRecetaRecord, RecetaRecord> DETALLE_RECETA__FK_DETALLE_RECETA_RECETA_2 = ForeignKeys0.DETALLE_RECETA__FK_DETALLE_RECETA_RECETA_2;
    public static final ForeignKey<DetalleRecetaRecord, InsumoRecord> DETALLE_RECETA__FK_DETALLE_RECETA_INSUMO_1 = ForeignKeys0.DETALLE_RECETA__FK_DETALLE_RECETA_INSUMO_1;
    public static final ForeignKey<DetalleRecetaRecord, UnidadMedidaRecord> DETALLE_RECETA__FK_DETALLE_RECETA_UNIDAD_MEDIDA_1 = ForeignKeys0.DETALLE_RECETA__FK_DETALLE_RECETA_UNIDAD_MEDIDA_1;
    public static final ForeignKey<DetalleRecetaRecord, RecetaRecord> DETALLE_RECETA__FK_DETALLE_RECETA_RECETA_1 = ForeignKeys0.DETALLE_RECETA__FK_DETALLE_RECETA_RECETA_1;
    public static final ForeignKey<DetalleVentaRecord, VentaRecord> DETALLE_VENTA__FK_DETALLE_VENTA_VENTA = ForeignKeys0.DETALLE_VENTA__FK_DETALLE_VENTA_VENTA;
    public static final ForeignKey<DetalleVentaRecord, ProductoRecord> DETALLE_VENTA__FK_DETALLE_VENTA_PRODUCTO_1 = ForeignKeys0.DETALLE_VENTA__FK_DETALLE_VENTA_PRODUCTO_1;
    public static final ForeignKey<DetalleVentaRecord, PromocionRecord> DETALLE_VENTA__FK_DETALLE_VENTA_PROMOCION_1 = ForeignKeys0.DETALLE_VENTA__FK_DETALLE_VENTA_PROMOCION_1;
    public static final ForeignKey<EmpleadoRecord, PuestoRecord> EMPLEADO__FK_EMPLEADO_PUESTO_1 = ForeignKeys0.EMPLEADO__FK_EMPLEADO_PUESTO_1;
    public static final ForeignKey<InsumoRecord, UnidadMedidaRecord> INSUMO__FK_INSUMO_UNIDAD_MEDIDA_1 = ForeignKeys0.INSUMO__FK_INSUMO_UNIDAD_MEDIDA_1;
    public static final ForeignKey<PagosCompraRecord, CompraRecord> PAGOS_COMPRA__FK_PAGOS_COMPRA_COMPRA_1 = ForeignKeys0.PAGOS_COMPRA__FK_PAGOS_COMPRA_COMPRA_1;
    public static final ForeignKey<PermisosRecord, ModuloRecord> PERMISOS__FK_PERMISOS_MODULO_1 = ForeignKeys0.PERMISOS__FK_PERMISOS_MODULO_1;
    public static final ForeignKey<PermisosRecord, EmpleadoRecord> PERMISOS__FK_PERMISOS_EMPLEADO_1 = ForeignKeys0.PERMISOS__FK_PERMISOS_EMPLEADO_1;
    public static final ForeignKey<ProductoRecord, CategoriaProductoRecord> PRODUCTO__FK_PRODUCTO_CATEGORIA_PRODUCTO_1 = ForeignKeys0.PRODUCTO__FK_PRODUCTO_CATEGORIA_PRODUCTO_1;
    public static final ForeignKey<ProductoRecord, RecetaRecord> PRODUCTO__FK_PRODUCTO_RECETA_1 = ForeignKeys0.PRODUCTO__FK_PRODUCTO_RECETA_1;
    public static final ForeignKey<ProductoRecord, InsumoRecord> PRODUCTO__FK_PRODUCTO_INSUMO_1 = ForeignKeys0.PRODUCTO__FK_PRODUCTO_INSUMO_1;
    public static final ForeignKey<RecetaRecord, UnidadMedidaRecord> RECETA__FK_RECETA_UNIDAD_MEDIDA_1 = ForeignKeys0.RECETA__FK_RECETA_UNIDAD_MEDIDA_1;
    public static final ForeignKey<ResolucionRecord, CajaRecord> RESOLUCION__FK_RESOLUCION_CAJA_1 = ForeignKeys0.RESOLUCION__FK_RESOLUCION_CAJA_1;
    public static final ForeignKey<UnidadMedidaRecord, MedidaRecord> UNIDAD_MEDIDA__FK_UNIDADMEDIDA_MEDIDA = ForeignKeys0.UNIDAD_MEDIDA__FK_UNIDADMEDIDA_MEDIDA;
    public static final ForeignKey<UnidadMedidaRecord, UnidadMedidaRecord> UNIDAD_MEDIDA__FK_UNIDADMEDIDA_UNIDADMEDIDA = ForeignKeys0.UNIDAD_MEDIDA__FK_UNIDADMEDIDA_UNIDADMEDIDA;
    public static final ForeignKey<UsuarioRecord, EmpleadoRecord> USUARIO__FK_USUARIO_EMPLEADO_1 = ForeignKeys0.USUARIO__FK_USUARIO_EMPLEADO_1;
    public static final ForeignKey<VentaRecord, ClienteRecord> VENTA__FK_VENTA_CLIENTE_1 = ForeignKeys0.VENTA__FK_VENTA_CLIENTE_1;
    public static final ForeignKey<VentaRecord, EmpleadoRecord> VENTA__FK_VENTA_EMPLEADO_1 = ForeignKeys0.VENTA__FK_VENTA_EMPLEADO_1;
    public static final ForeignKey<VentaRecord, ResolucionRecord> VENTA__FK_VENTA_RESOLUCION_1 = ForeignKeys0.VENTA__FK_VENTA_RESOLUCION_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CajaRecord, Integer> IDENTITY_CAJA = createIdentity(Caja.CAJA, Caja.CAJA.IDCAJA);
        public static Identity<CategoriaProductoRecord, Integer> IDENTITY_CATEGORIA_PRODUCTO = createIdentity(CategoriaProducto.CATEGORIA_PRODUCTO, CategoriaProducto.CATEGORIA_PRODUCTO.IDCATEGORIA);
        public static Identity<ClienteRecord, Integer> IDENTITY_CLIENTE = createIdentity(Cliente.CLIENTE, Cliente.CLIENTE.IDCLIENTE);
        public static Identity<CompraRecord, Integer> IDENTITY_COMPRA = createIdentity(Compra.COMPRA, Compra.COMPRA.IDCOMPRA);
        public static Identity<CostosIndirectosRecord, Integer> IDENTITY_COSTOS_INDIRECTOS = createIdentity(CostosIndirectos.COSTOS_INDIRECTOS, CostosIndirectos.COSTOS_INDIRECTOS.IDCOSTO);
        public static Identity<CotizacionRecord, Integer> IDENTITY_COTIZACION = createIdentity(Cotizacion.COTIZACION, Cotizacion.COTIZACION.IDCOTIZACION);
        public static Identity<EmpleadoRecord, Integer> IDENTITY_EMPLEADO = createIdentity(Empleado.EMPLEADO, Empleado.EMPLEADO.IDEMPLEADO);
        public static Identity<InsumoRecord, Integer> IDENTITY_INSUMO = createIdentity(Insumo.INSUMO, Insumo.INSUMO.IDINSUMO);
        public static Identity<ModuloRecord, Integer> IDENTITY_MODULO = createIdentity(Modulo.MODULO, Modulo.MODULO.IDMODULO);
        public static Identity<ProductoRecord, Integer> IDENTITY_PRODUCTO = createIdentity(Producto.PRODUCTO, Producto.PRODUCTO.IDPRODUCTO);
        public static Identity<PromocionRecord, Integer> IDENTITY_PROMOCION = createIdentity(Promocion.PROMOCION, Promocion.PROMOCION.IDPROMOCION);
        public static Identity<ProveedorRecord, Integer> IDENTITY_PROVEEDOR = createIdentity(Proveedor.PROVEEDOR, Proveedor.PROVEEDOR.IDPROVEEDOR);
        public static Identity<PuestoRecord, Integer> IDENTITY_PUESTO = createIdentity(Puesto.PUESTO, Puesto.PUESTO.IDPUESTO);
        public static Identity<RecetaRecord, Integer> IDENTITY_RECETA = createIdentity(Receta.RECETA, Receta.RECETA.IDRECETA);
        public static Identity<ResolucionRecord, Integer> IDENTITY_RESOLUCION = createIdentity(Resolucion.RESOLUCION, Resolucion.RESOLUCION.IDRESOLUCION);
        public static Identity<VentaRecord, Integer> IDENTITY_VENTA = createIdentity(Venta.VENTA, Venta.VENTA.IDVENTA);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CajaRecord> CAJA_PKEY = createUniqueKey(Caja.CAJA, "caja_pkey", Caja.CAJA.IDCAJA);
        public static final UniqueKey<CategoriaProductoRecord> CATEGORIA_PRODUCTO_PKEY = createUniqueKey(CategoriaProducto.CATEGORIA_PRODUCTO, "categoria_producto_pkey", CategoriaProducto.CATEGORIA_PRODUCTO.IDCATEGORIA);
        public static final UniqueKey<ClienteRecord> PK_CLIENTE = createUniqueKey(Cliente.CLIENTE, "pk_cliente", Cliente.CLIENTE.IDCLIENTE);
        public static final UniqueKey<CompraRecord> COMPRA_PKEY = createUniqueKey(Compra.COMPRA, "compra_pkey", Compra.COMPRA.IDCOMPRA);
        public static final UniqueKey<CostosIndirectosRecord> COSTOS_INDIRECTOS_PKEY = createUniqueKey(CostosIndirectos.COSTOS_INDIRECTOS, "costos_indirectos_pkey", CostosIndirectos.COSTOS_INDIRECTOS.IDCOSTO);
        public static final UniqueKey<CotizacionRecord> PK_COTIZACION = createUniqueKey(Cotizacion.COTIZACION, "pk_cotizacion", Cotizacion.COTIZACION.IDCOTIZACION);
        public static final UniqueKey<EmpleadoRecord> PK_EMPLEADO = createUniqueKey(Empleado.EMPLEADO, "pk_empleado", Empleado.EMPLEADO.IDEMPLEADO);
        public static final UniqueKey<EmpresaRecord> PK_EMPRESA = createUniqueKey(Empresa.EMPRESA, "pk_empresa", Empresa.EMPRESA.IDEMPRESA);
        public static final UniqueKey<InsumoRecord> INSUMO_PKEY = createUniqueKey(Insumo.INSUMO, "insumo_pkey", Insumo.INSUMO.IDINSUMO);
        public static final UniqueKey<MedidaRecord> PK_MEDIDA = createUniqueKey(Medida.MEDIDA, "pk_medida", Medida.MEDIDA.IDMEDIDA);
        public static final UniqueKey<ModuloRecord> PK_ROL = createUniqueKey(Modulo.MODULO, "pk_rol", Modulo.MODULO.IDMODULO);
        public static final UniqueKey<ProductoRecord> PRODUCTO_PKEY = createUniqueKey(Producto.PRODUCTO, "producto_pkey", Producto.PRODUCTO.IDPRODUCTO);
        public static final UniqueKey<PromocionRecord> PROMOCION_PKEY = createUniqueKey(Promocion.PROMOCION, "promocion_pkey", Promocion.PROMOCION.IDPROMOCION);
        public static final UniqueKey<ProveedorRecord> PROVEEDOR_PKEY = createUniqueKey(Proveedor.PROVEEDOR, "proveedor_pkey", Proveedor.PROVEEDOR.IDPROVEEDOR);
        public static final UniqueKey<PuestoRecord> PUESTO_PKEY = createUniqueKey(Puesto.PUESTO, "puesto_pkey", Puesto.PUESTO.IDPUESTO);
        public static final UniqueKey<RecetaRecord> RECETA_PKEY = createUniqueKey(Receta.RECETA, "receta_pkey", Receta.RECETA.IDRECETA);
        public static final UniqueKey<ResolucionRecord> RESOLUCION_PKEY = createUniqueKey(Resolucion.RESOLUCION, "resolucion_pkey", Resolucion.RESOLUCION.IDRESOLUCION);
        public static final UniqueKey<UnidadMedidaRecord> PK_UNIDADMEDIDA = createUniqueKey(UnidadMedida.UNIDAD_MEDIDA, "pk_unidadmedida", UnidadMedida.UNIDAD_MEDIDA.IDUNIDAD);
        public static final UniqueKey<VentaRecord> PK_VENTA = createUniqueKey(Venta.VENTA, "pk_venta", Venta.VENTA.IDVENTA);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BitacoraCajaRecord, CajaRecord> BITACORA_CAJA__FK_BITACORA_CAJA = createForeignKey(com.pereira.manolos.datos.database.Keys.CAJA_PKEY, BitacoraCaja.BITACORA_CAJA, "bitacora_caja__fk_bitacora_caja", BitacoraCaja.BITACORA_CAJA.IDCAJA);
        public static final ForeignKey<ClienteCreditofiscalRecord, ClienteRecord> CLIENTE_CREDITOFISCAL__FK_CLIENTE_CREDITOFISCAL_CLIENTE_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_CLIENTE, ClienteCreditofiscal.CLIENTE_CREDITOFISCAL, "cliente_creditofiscal__fk_cliente_creditofiscal_cliente_1", ClienteCreditofiscal.CLIENTE_CREDITOFISCAL.IDCLIENTE);
        public static final ForeignKey<CompraRecord, ProveedorRecord> COMPRA__FK_COMPRA_PROVEEDOR_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PROVEEDOR_PKEY, Compra.COMPRA, "compra__fk_compra_proveedor_1", Compra.COMPRA.IDPROVEEDOR);
        public static final ForeignKey<CotizacionRecord, ClienteRecord> COTIZACION__FK_COTIZACION_CLIENTE_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_CLIENTE, Cotizacion.COTIZACION, "cotizacion__fk_cotizacion_cliente_1", Cotizacion.COTIZACION.IDCLIENTE);
        public static final ForeignKey<DetalleCompraRecord, CompraRecord> DETALLE_COMPRA__FK_DETALLE_COMPRA_COMPRA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.COMPRA_PKEY, DetalleCompra.DETALLE_COMPRA, "detalle_compra__fk_detalle_compra_compra_1", DetalleCompra.DETALLE_COMPRA.IDCOMPRA);
        public static final ForeignKey<DetalleCompraRecord, InsumoRecord> DETALLE_COMPRA__FK_DETALLE_COMPRA_INSUMO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.INSUMO_PKEY, DetalleCompra.DETALLE_COMPRA, "detalle_compra__fk_detalle_compra_insumo_1", DetalleCompra.DETALLE_COMPRA.IDINSUMO);
        public static final ForeignKey<DetalleCotizacionRecord, PromocionRecord> DETALLE_COTIZACION__FK_DETALLE_COTIZA_PROMO = createForeignKey(com.pereira.manolos.datos.database.Keys.PROMOCION_PKEY, DetalleCotizacion.DETALLE_COTIZACION, "detalle_cotizacion__fk_detalle_cotiza_promo", DetalleCotizacion.DETALLE_COTIZACION.IDCOTIZACION);
        public static final ForeignKey<DetalleCotizacionRecord, CotizacionRecord> DETALLE_COTIZACION__FK_DETALLE_COTIZACION_COTIZACION = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_COTIZACION, DetalleCotizacion.DETALLE_COTIZACION, "detalle_cotizacion__fk_detalle_cotizacion_cotizacion", DetalleCotizacion.DETALLE_COTIZACION.IDCOTIZACION);
        public static final ForeignKey<DetalleCotizacionRecord, ProductoRecord> DETALLE_COTIZACION__FK_DETALLE_COTIZACION_PRODUCTO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PRODUCTO_PKEY, DetalleCotizacion.DETALLE_COTIZACION, "detalle_cotizacion__fk_detalle_cotizacion_producto_1", DetalleCotizacion.DETALLE_COTIZACION.IDPRODUCTO);
        public static final ForeignKey<DetallePromocionRecord, PromocionRecord> DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PROMOCION_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PROMOCION_PKEY, DetallePromocion.DETALLE_PROMOCION, "detalle_promocion__fk_detalle_promocion_promocion_1", DetallePromocion.DETALLE_PROMOCION.IDPROMOCION);
        public static final ForeignKey<DetallePromocionRecord, ProductoRecord> DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PRODUCTO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PRODUCTO_PKEY, DetallePromocion.DETALLE_PROMOCION, "detalle_promocion__fk_detalle_promocion_producto_1", DetallePromocion.DETALLE_PROMOCION.IDPRODUCTO);
        public static final ForeignKey<DetalleRecetaRecord, RecetaRecord> DETALLE_RECETA__FK_DETALLE_RECETA_RECETA_2 = createForeignKey(com.pereira.manolos.datos.database.Keys.RECETA_PKEY, DetalleReceta.DETALLE_RECETA, "detalle_receta__fk_detalle_receta_receta_2", DetalleReceta.DETALLE_RECETA.IDRECETA);
        public static final ForeignKey<DetalleRecetaRecord, InsumoRecord> DETALLE_RECETA__FK_DETALLE_RECETA_INSUMO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.INSUMO_PKEY, DetalleReceta.DETALLE_RECETA, "detalle_receta__fk_detalle_receta_insumo_1", DetalleReceta.DETALLE_RECETA.INGREDIENTE);
        public static final ForeignKey<DetalleRecetaRecord, UnidadMedidaRecord> DETALLE_RECETA__FK_DETALLE_RECETA_UNIDAD_MEDIDA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_UNIDADMEDIDA, DetalleReceta.DETALLE_RECETA, "detalle_receta__fk_detalle_receta_unidad_medida_1", DetalleReceta.DETALLE_RECETA.IDUNIDAD);
        public static final ForeignKey<DetalleRecetaRecord, RecetaRecord> DETALLE_RECETA__FK_DETALLE_RECETA_RECETA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.RECETA_PKEY, DetalleReceta.DETALLE_RECETA, "detalle_receta__fk_detalle_receta_receta_1", DetalleReceta.DETALLE_RECETA.INGREDIENTERECETA);
        public static final ForeignKey<DetalleVentaRecord, VentaRecord> DETALLE_VENTA__FK_DETALLE_VENTA_VENTA = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_VENTA, DetalleVenta.DETALLE_VENTA, "detalle_venta__fk_detalle_venta_venta", DetalleVenta.DETALLE_VENTA.IDVENTA);
        public static final ForeignKey<DetalleVentaRecord, ProductoRecord> DETALLE_VENTA__FK_DETALLE_VENTA_PRODUCTO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PRODUCTO_PKEY, DetalleVenta.DETALLE_VENTA, "detalle_venta__fk_detalle_venta_producto_1", DetalleVenta.DETALLE_VENTA.IDPRODUCTO);
        public static final ForeignKey<DetalleVentaRecord, PromocionRecord> DETALLE_VENTA__FK_DETALLE_VENTA_PROMOCION_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PROMOCION_PKEY, DetalleVenta.DETALLE_VENTA, "detalle_venta__fk_detalle_venta_promocion_1", DetalleVenta.DETALLE_VENTA.IDPROMOCION);
        public static final ForeignKey<EmpleadoRecord, PuestoRecord> EMPLEADO__FK_EMPLEADO_PUESTO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PUESTO_PKEY, Empleado.EMPLEADO, "empleado__fk_empleado_puesto_1", Empleado.EMPLEADO.IDPUESTO);
        public static final ForeignKey<InsumoRecord, UnidadMedidaRecord> INSUMO__FK_INSUMO_UNIDAD_MEDIDA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_UNIDADMEDIDA, Insumo.INSUMO, "insumo__fk_insumo_unidad_medida_1", Insumo.INSUMO.IDUNIDAD);
        public static final ForeignKey<PagosCompraRecord, CompraRecord> PAGOS_COMPRA__FK_PAGOS_COMPRA_COMPRA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.COMPRA_PKEY, PagosCompra.PAGOS_COMPRA, "pagos_compra__fk_pagos_compra_compra_1", PagosCompra.PAGOS_COMPRA.IDCOMPRA);
        public static final ForeignKey<PermisosRecord, ModuloRecord> PERMISOS__FK_PERMISOS_MODULO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_ROL, Permisos.PERMISOS, "permisos__fk_permisos_modulo_1", Permisos.PERMISOS.IDMODULO);
        public static final ForeignKey<PermisosRecord, EmpleadoRecord> PERMISOS__FK_PERMISOS_EMPLEADO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_EMPLEADO, Permisos.PERMISOS, "permisos__fk_permisos_empleado_1", Permisos.PERMISOS.IDEMPLEADO);
        public static final ForeignKey<ProductoRecord, CategoriaProductoRecord> PRODUCTO__FK_PRODUCTO_CATEGORIA_PRODUCTO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.CATEGORIA_PRODUCTO_PKEY, Producto.PRODUCTO, "producto__fk_producto_categoria_producto_1", Producto.PRODUCTO.IDCATEGORIA);
        public static final ForeignKey<ProductoRecord, RecetaRecord> PRODUCTO__FK_PRODUCTO_RECETA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.RECETA_PKEY, Producto.PRODUCTO, "producto__fk_producto_receta_1", Producto.PRODUCTO.IDRECETA);
        public static final ForeignKey<ProductoRecord, InsumoRecord> PRODUCTO__FK_PRODUCTO_INSUMO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.INSUMO_PKEY, Producto.PRODUCTO, "producto__fk_producto_insumo_1", Producto.PRODUCTO.IDINSUMO);
        public static final ForeignKey<RecetaRecord, UnidadMedidaRecord> RECETA__FK_RECETA_UNIDAD_MEDIDA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_UNIDADMEDIDA, Receta.RECETA, "receta__fk_receta_unidad_medida_1", Receta.RECETA.IDUNIDAD);
        public static final ForeignKey<ResolucionRecord, CajaRecord> RESOLUCION__FK_RESOLUCION_CAJA_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.CAJA_PKEY, Resolucion.RESOLUCION, "resolucion__fk_resolucion_caja_1", Resolucion.RESOLUCION.IDCAJA);
        public static final ForeignKey<UnidadMedidaRecord, MedidaRecord> UNIDAD_MEDIDA__FK_UNIDADMEDIDA_MEDIDA = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_MEDIDA, UnidadMedida.UNIDAD_MEDIDA, "unidad_medida__fk_unidadmedida_medida", UnidadMedida.UNIDAD_MEDIDA.IDMEDIDA);
        public static final ForeignKey<UnidadMedidaRecord, UnidadMedidaRecord> UNIDAD_MEDIDA__FK_UNIDADMEDIDA_UNIDADMEDIDA = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_UNIDADMEDIDA, UnidadMedida.UNIDAD_MEDIDA, "unidad_medida__fk_unidadmedida_unidadmedida", UnidadMedida.UNIDAD_MEDIDA.UNIDADPADRE);
        public static final ForeignKey<UsuarioRecord, EmpleadoRecord> USUARIO__FK_USUARIO_EMPLEADO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_EMPLEADO, Usuario.USUARIO, "usuario__fk_usuario_empleado_1", Usuario.USUARIO.IDEMPLEADO);
        public static final ForeignKey<VentaRecord, ClienteRecord> VENTA__FK_VENTA_CLIENTE_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_CLIENTE, Venta.VENTA, "venta__fk_venta_cliente_1", Venta.VENTA.IDCLIENTE);
        public static final ForeignKey<VentaRecord, EmpleadoRecord> VENTA__FK_VENTA_EMPLEADO_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.PK_EMPLEADO, Venta.VENTA, "venta__fk_venta_empleado_1", Venta.VENTA.IDEMPLEADO);
        public static final ForeignKey<VentaRecord, ResolucionRecord> VENTA__FK_VENTA_RESOLUCION_1 = createForeignKey(com.pereira.manolos.datos.database.Keys.RESOLUCION_PKEY, Venta.VENTA, "venta__fk_venta_resolucion_1", Venta.VENTA.IDRESOLUCION);
    }
}
