/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database;


import com.pereira.manolos.datos.database.tables.BitacoraCaja;
import com.pereira.manolos.datos.database.tables.Caja;
import com.pereira.manolos.datos.database.tables.CategoriaProducto;
import com.pereira.manolos.datos.database.tables.Cliente;
import com.pereira.manolos.datos.database.tables.ClienteCreditofiscal;
import com.pereira.manolos.datos.database.tables.Compra;
import com.pereira.manolos.datos.database.tables.CostosIndirectos;
import com.pereira.manolos.datos.database.tables.Cotizacion;
import com.pereira.manolos.datos.database.tables.DetalleCompra;
import com.pereira.manolos.datos.database.tables.DetalleCotizacion;
import com.pereira.manolos.datos.database.tables.DetallePromocion;
import com.pereira.manolos.datos.database.tables.DetalleReceta;
import com.pereira.manolos.datos.database.tables.DetalleVenta;
import com.pereira.manolos.datos.database.tables.Empleado;
import com.pereira.manolos.datos.database.tables.Empresa;
import com.pereira.manolos.datos.database.tables.Insumo;
import com.pereira.manolos.datos.database.tables.Medida;
import com.pereira.manolos.datos.database.tables.Modulo;
import com.pereira.manolos.datos.database.tables.MovimientoCaja;
import com.pereira.manolos.datos.database.tables.PagosCompra;
import com.pereira.manolos.datos.database.tables.Permisos;
import com.pereira.manolos.datos.database.tables.Producto;
import com.pereira.manolos.datos.database.tables.Promocion;
import com.pereira.manolos.datos.database.tables.Proveedor;
import com.pereira.manolos.datos.database.tables.Puesto;
import com.pereira.manolos.datos.database.tables.Receta;
import com.pereira.manolos.datos.database.tables.Resolucion;
import com.pereira.manolos.datos.database.tables.UnidadMedida;
import com.pereira.manolos.datos.database.tables.Usuario;
import com.pereira.manolos.datos.database.tables.VAsociadoReceta;
import com.pereira.manolos.datos.database.tables.VCajaMovimiento;
import com.pereira.manolos.datos.database.tables.VCif;
import com.pereira.manolos.datos.database.tables.VCompras;
import com.pereira.manolos.datos.database.tables.VCotizacion;
import com.pereira.manolos.datos.database.tables.VDetalleCompra;
import com.pereira.manolos.datos.database.tables.VDetalleCotizacion;
import com.pereira.manolos.datos.database.tables.VDetalleReceta;
import com.pereira.manolos.datos.database.tables.VDetalleVenta;
import com.pereira.manolos.datos.database.tables.VEmpleados;
import com.pereira.manolos.datos.database.tables.VIngredientes;
import com.pereira.manolos.datos.database.tables.VInsumos;
import com.pereira.manolos.datos.database.tables.VMedidas;
import com.pereira.manolos.datos.database.tables.VModHora;
import com.pereira.manolos.datos.database.tables.VRecetas;
import com.pereira.manolos.datos.database.tables.VVenta;
import com.pereira.manolos.datos.database.tables.Venta;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bitacora_caja</code>.
     */
    public static final BitacoraCaja BITACORA_CAJA = com.pereira.manolos.datos.database.tables.BitacoraCaja.BITACORA_CAJA;

    /**
     * The table <code>public.caja</code>.
     */
    public static final Caja CAJA = com.pereira.manolos.datos.database.tables.Caja.CAJA;

    /**
     * The table <code>public.categoria_producto</code>.
     */
    public static final CategoriaProducto CATEGORIA_PRODUCTO = com.pereira.manolos.datos.database.tables.CategoriaProducto.CATEGORIA_PRODUCTO;

    /**
     * The table <code>public.cliente</code>.
     */
    public static final Cliente CLIENTE = com.pereira.manolos.datos.database.tables.Cliente.CLIENTE;

    /**
     * The table <code>public.cliente_creditofiscal</code>.
     */
    public static final ClienteCreditofiscal CLIENTE_CREDITOFISCAL = com.pereira.manolos.datos.database.tables.ClienteCreditofiscal.CLIENTE_CREDITOFISCAL;

    /**
     * The table <code>public.compra</code>.
     */
    public static final Compra COMPRA = com.pereira.manolos.datos.database.tables.Compra.COMPRA;

    /**
     * The table <code>public.costos_indirectos</code>.
     */
    public static final CostosIndirectos COSTOS_INDIRECTOS = com.pereira.manolos.datos.database.tables.CostosIndirectos.COSTOS_INDIRECTOS;

    /**
     * The table <code>public.cotizacion</code>.
     */
    public static final Cotizacion COTIZACION = com.pereira.manolos.datos.database.tables.Cotizacion.COTIZACION;

    /**
     * The table <code>public.detalle_compra</code>.
     */
    public static final DetalleCompra DETALLE_COMPRA = com.pereira.manolos.datos.database.tables.DetalleCompra.DETALLE_COMPRA;

    /**
     * The table <code>public.detalle_cotizacion</code>.
     */
    public static final DetalleCotizacion DETALLE_COTIZACION = com.pereira.manolos.datos.database.tables.DetalleCotizacion.DETALLE_COTIZACION;

    /**
     * The table <code>public.detalle_promocion</code>.
     */
    public static final DetallePromocion DETALLE_PROMOCION = com.pereira.manolos.datos.database.tables.DetallePromocion.DETALLE_PROMOCION;

    /**
     * The table <code>public.detalle_receta</code>.
     */
    public static final DetalleReceta DETALLE_RECETA = com.pereira.manolos.datos.database.tables.DetalleReceta.DETALLE_RECETA;

    /**
     * The table <code>public.detalle_venta</code>.
     */
    public static final DetalleVenta DETALLE_VENTA = com.pereira.manolos.datos.database.tables.DetalleVenta.DETALLE_VENTA;

    /**
     * The table <code>public.empleado</code>.
     */
    public static final Empleado EMPLEADO = com.pereira.manolos.datos.database.tables.Empleado.EMPLEADO;

    /**
     * The table <code>public.empresa</code>.
     */
    public static final Empresa EMPRESA = com.pereira.manolos.datos.database.tables.Empresa.EMPRESA;

    /**
     * The table <code>public.insumo</code>.
     */
    public static final Insumo INSUMO = com.pereira.manolos.datos.database.tables.Insumo.INSUMO;

    /**
     * The table <code>public.medida</code>.
     */
    public static final Medida MEDIDA = com.pereira.manolos.datos.database.tables.Medida.MEDIDA;

    /**
     * The table <code>public.modulo</code>.
     */
    public static final Modulo MODULO = com.pereira.manolos.datos.database.tables.Modulo.MODULO;

    /**
     * The table <code>public.movimiento_caja</code>.
     */
    public static final MovimientoCaja MOVIMIENTO_CAJA = com.pereira.manolos.datos.database.tables.MovimientoCaja.MOVIMIENTO_CAJA;

    /**
     * The table <code>public.pagos_compra</code>.
     */
    public static final PagosCompra PAGOS_COMPRA = com.pereira.manolos.datos.database.tables.PagosCompra.PAGOS_COMPRA;

    /**
     * The table <code>public.permisos</code>.
     */
    public static final Permisos PERMISOS = com.pereira.manolos.datos.database.tables.Permisos.PERMISOS;

    /**
     * The table <code>public.producto</code>.
     */
    public static final Producto PRODUCTO = com.pereira.manolos.datos.database.tables.Producto.PRODUCTO;

    /**
     * The table <code>public.promocion</code>.
     */
    public static final Promocion PROMOCION = com.pereira.manolos.datos.database.tables.Promocion.PROMOCION;

    /**
     * The table <code>public.proveedor</code>.
     */
    public static final Proveedor PROVEEDOR = com.pereira.manolos.datos.database.tables.Proveedor.PROVEEDOR;

    /**
     * The table <code>public.puesto</code>.
     */
    public static final Puesto PUESTO = com.pereira.manolos.datos.database.tables.Puesto.PUESTO;

    /**
     * The table <code>public.receta</code>.
     */
    public static final Receta RECETA = com.pereira.manolos.datos.database.tables.Receta.RECETA;

    /**
     * The table <code>public.resolucion</code>.
     */
    public static final Resolucion RESOLUCION = com.pereira.manolos.datos.database.tables.Resolucion.RESOLUCION;

    /**
     * The table <code>public.unidad_medida</code>.
     */
    public static final UnidadMedida UNIDAD_MEDIDA = com.pereira.manolos.datos.database.tables.UnidadMedida.UNIDAD_MEDIDA;

    /**
     * The table <code>public.usuario</code>.
     */
    public static final Usuario USUARIO = com.pereira.manolos.datos.database.tables.Usuario.USUARIO;

    /**
     * The table <code>public.v_asociado_receta</code>.
     */
    public static final VAsociadoReceta V_ASOCIADO_RECETA = com.pereira.manolos.datos.database.tables.VAsociadoReceta.V_ASOCIADO_RECETA;

    /**
     * The table <code>public.v_caja_movimiento</code>.
     */
    public static final VCajaMovimiento V_CAJA_MOVIMIENTO = com.pereira.manolos.datos.database.tables.VCajaMovimiento.V_CAJA_MOVIMIENTO;

    /**
     * The table <code>public.v_cif</code>.
     */
    public static final VCif V_CIF = com.pereira.manolos.datos.database.tables.VCif.V_CIF;

    /**
     * The table <code>public.v_compras</code>.
     */
    public static final VCompras V_COMPRAS = com.pereira.manolos.datos.database.tables.VCompras.V_COMPRAS;

    /**
     * The table <code>public.v_cotizacion</code>.
     */
    public static final VCotizacion V_COTIZACION = com.pereira.manolos.datos.database.tables.VCotizacion.V_COTIZACION;

    /**
     * The table <code>public.v_detalle_compra</code>.
     */
    public static final VDetalleCompra V_DETALLE_COMPRA = com.pereira.manolos.datos.database.tables.VDetalleCompra.V_DETALLE_COMPRA;

    /**
     * The table <code>public.v_detalle_cotizacion</code>.
     */
    public static final VDetalleCotizacion V_DETALLE_COTIZACION = com.pereira.manolos.datos.database.tables.VDetalleCotizacion.V_DETALLE_COTIZACION;

    /**
     * The table <code>public.v_detalle_receta</code>.
     */
    public static final VDetalleReceta V_DETALLE_RECETA = com.pereira.manolos.datos.database.tables.VDetalleReceta.V_DETALLE_RECETA;

    /**
     * The table <code>public.v_detalle_venta</code>.
     */
    public static final VDetalleVenta V_DETALLE_VENTA = com.pereira.manolos.datos.database.tables.VDetalleVenta.V_DETALLE_VENTA;

    /**
     * The table <code>public.v_empleados</code>.
     */
    public static final VEmpleados V_EMPLEADOS = com.pereira.manolos.datos.database.tables.VEmpleados.V_EMPLEADOS;

    /**
     * The table <code>public.v_ingredientes</code>.
     */
    public static final VIngredientes V_INGREDIENTES = com.pereira.manolos.datos.database.tables.VIngredientes.V_INGREDIENTES;

    /**
     * The table <code>public.v_insumos</code>.
     */
    public static final VInsumos V_INSUMOS = com.pereira.manolos.datos.database.tables.VInsumos.V_INSUMOS;

    /**
     * The table <code>public.v_medidas</code>.
     */
    public static final VMedidas V_MEDIDAS = com.pereira.manolos.datos.database.tables.VMedidas.V_MEDIDAS;

    /**
     * The table <code>public.v_mod_hora</code>.
     */
    public static final VModHora V_MOD_HORA = com.pereira.manolos.datos.database.tables.VModHora.V_MOD_HORA;

    /**
     * The table <code>public.v_recetas</code>.
     */
    public static final VRecetas V_RECETAS = com.pereira.manolos.datos.database.tables.VRecetas.V_RECETAS;

    /**
     * The table <code>public.v_venta</code>.
     */
    public static final VVenta V_VENTA = com.pereira.manolos.datos.database.tables.VVenta.V_VENTA;

    /**
     * The table <code>public.venta</code>.
     */
    public static final Venta VENTA = com.pereira.manolos.datos.database.tables.Venta.VENTA;
}
