/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Keys;
import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.ClienteCreditofiscalRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteCreditofiscal extends TableImpl<ClienteCreditofiscalRecord> {

    private static final long serialVersionUID = -1928819568;

    /**
     * The reference instance of <code>public.cliente_creditofiscal</code>
     */
    public static final ClienteCreditofiscal CLIENTE_CREDITOFISCAL = new ClienteCreditofiscal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClienteCreditofiscalRecord> getRecordType() {
        return ClienteCreditofiscalRecord.class;
    }

    /**
     * The column <code>public.cliente_creditofiscal.idcliente</code>.
     */
    public final TableField<ClienteCreditofiscalRecord, Integer> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.cliente_creditofiscal.giro</code>.
     */
    public final TableField<ClienteCreditofiscalRecord, String> GIRO = createField("giro", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente_creditofiscal.nrc</code>.
     */
    public final TableField<ClienteCreditofiscalRecord, String> NRC = createField("nrc", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

    /**
     * The column <code>public.cliente_creditofiscal.nit</code>.
     */
    public final TableField<ClienteCreditofiscalRecord, String> NIT = createField("nit", org.jooq.impl.SQLDataType.VARCHAR.length(18), this, "");

    /**
     * The column <code>public.cliente_creditofiscal.representante</code>.
     */
    public final TableField<ClienteCreditofiscalRecord, String> REPRESENTANTE = createField("representante", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.cliente_creditofiscal</code> table reference
     */
    public ClienteCreditofiscal() {
        this("cliente_creditofiscal", null);
    }

    /**
     * Create an aliased <code>public.cliente_creditofiscal</code> table reference
     */
    public ClienteCreditofiscal(String alias) {
        this(alias, CLIENTE_CREDITOFISCAL);
    }

    private ClienteCreditofiscal(String alias, Table<ClienteCreditofiscalRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClienteCreditofiscal(String alias, Table<ClienteCreditofiscalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClienteCreditofiscalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClienteCreditofiscalRecord, ?>>asList(Keys.CLIENTE_CREDITOFISCAL__FK_CLIENTE_CREDITOFISCAL_CLIENTE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteCreditofiscal as(String alias) {
        return new ClienteCreditofiscal(alias, this);
    }

    /**
     * Rename this table
     */
    public ClienteCreditofiscal rename(String name) {
        return new ClienteCreditofiscal(name, null);
    }
}
