/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Keys;
import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.DetallePromocionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetallePromocion extends TableImpl<DetallePromocionRecord> {

    private static final long serialVersionUID = 26387577;

    /**
     * The reference instance of <code>public.detalle_promocion</code>
     */
    public static final DetallePromocion DETALLE_PROMOCION = new DetallePromocion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DetallePromocionRecord> getRecordType() {
        return DetallePromocionRecord.class;
    }

    /**
     * The column <code>public.detalle_promocion.idpromocion</code>.
     */
    public final TableField<DetallePromocionRecord, Integer> IDPROMOCION = createField("idpromocion", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalle_promocion.idproducto</code>.
     */
    public final TableField<DetallePromocionRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalle_promocion.cantidad</code>.
     */
    public final TableField<DetallePromocionRecord, Integer> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalle_promocion.tipo</code>.
     */
    public final TableField<DetallePromocionRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.detalle_promocion</code> table reference
     */
    public DetallePromocion() {
        this("detalle_promocion", null);
    }

    /**
     * Create an aliased <code>public.detalle_promocion</code> table reference
     */
    public DetallePromocion(String alias) {
        this(alias, DETALLE_PROMOCION);
    }

    private DetallePromocion(String alias, Table<DetallePromocionRecord> aliased) {
        this(alias, aliased, null);
    }

    private DetallePromocion(String alias, Table<DetallePromocionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DetallePromocionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DetallePromocionRecord, ?>>asList(Keys.DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PROMOCION_1, Keys.DETALLE_PROMOCION__FK_DETALLE_PROMOCION_PRODUCTO_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetallePromocion as(String alias) {
        return new DetallePromocion(alias, this);
    }

    /**
     * Rename this table
     */
    public DetallePromocion rename(String name) {
        return new DetallePromocion(name, null);
    }
}
