/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Keys;
import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.PermisosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permisos extends TableImpl<PermisosRecord> {

    private static final long serialVersionUID = 1747072477;

    /**
     * The reference instance of <code>public.permisos</code>
     */
    public static final Permisos PERMISOS = new Permisos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermisosRecord> getRecordType() {
        return PermisosRecord.class;
    }

    /**
     * The column <code>public.permisos.idmodulo</code>.
     */
    public final TableField<PermisosRecord, Integer> IDMODULO = createField("idmodulo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.permisos.permiso</code>.
     */
    public final TableField<PermisosRecord, Boolean> PERMISO = createField("permiso", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.permisos.idempleado</code>.
     */
    public final TableField<PermisosRecord, Integer> IDEMPLEADO = createField("idempleado", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.permisos</code> table reference
     */
    public Permisos() {
        this("permisos", null);
    }

    /**
     * Create an aliased <code>public.permisos</code> table reference
     */
    public Permisos(String alias) {
        this(alias, PERMISOS);
    }

    private Permisos(String alias, Table<PermisosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Permisos(String alias, Table<PermisosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PermisosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PermisosRecord, ?>>asList(Keys.PERMISOS__FK_PERMISOS_MODULO_1, Keys.PERMISOS__FK_PERMISOS_EMPLEADO_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Permisos as(String alias) {
        return new Permisos(alias, this);
    }

    /**
     * Rename this table
     */
    public Permisos rename(String name) {
        return new Permisos(name, null);
    }
}
