/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Keys;
import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.RecetaRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Receta extends TableImpl<RecetaRecord> {

    private static final long serialVersionUID = 423190313;

    /**
     * The reference instance of <code>public.receta</code>
     */
    public static final Receta RECETA = new Receta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecetaRecord> getRecordType() {
        return RecetaRecord.class;
    }

    /**
     * The column <code>public.receta.idreceta</code>.
     */
    public final TableField<RecetaRecord, Integer> IDRECETA = createField("idreceta", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('receta_idreceta_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.receta.nombre</code>.
     */
    public final TableField<RecetaRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.receta.tiporeceta</code>.
     */
    public final TableField<RecetaRecord, String> TIPORECETA = createField("tiporeceta", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.receta.idunidad</code>.
     */
    public final TableField<RecetaRecord, Integer> IDUNIDAD = createField("idunidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.receta.costo</code>.
     */
    public final TableField<RecetaRecord, BigDecimal> COSTO = createField("costo", org.jooq.impl.SQLDataType.NUMERIC.precision(7, 4), this, "");

    /**
     * The column <code>public.receta.baja</code>.
     */
    public final TableField<RecetaRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.receta.stock</code>.
     */
    public final TableField<RecetaRecord, Double> STOCK = createField("stock", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.receta.rendimiento</code>.
     */
    public final TableField<RecetaRecord, Double> RENDIMIENTO = createField("rendimiento", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.receta.estimadomensual</code>.
     */
    public final TableField<RecetaRecord, Double> ESTIMADOMENSUAL = createField("estimadomensual", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.receta.maximo</code>.
     */
    public final TableField<RecetaRecord, Double> MAXIMO = createField("maximo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.receta.minimo</code>.
     */
    public final TableField<RecetaRecord, Double> MINIMO = createField("minimo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.receta.horas</code>.
     */
    public final TableField<RecetaRecord, Integer> HORAS = createField("horas", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.receta.minutos</code>.
     */
    public final TableField<RecetaRecord, Integer> MINUTOS = createField("minutos", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.receta</code> table reference
     */
    public Receta() {
        this("receta", null);
    }

    /**
     * Create an aliased <code>public.receta</code> table reference
     */
    public Receta(String alias) {
        this(alias, RECETA);
    }

    private Receta(String alias, Table<RecetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Receta(String alias, Table<RecetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RecetaRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RECETA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RecetaRecord> getPrimaryKey() {
        return Keys.RECETA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RecetaRecord>> getKeys() {
        return Arrays.<UniqueKey<RecetaRecord>>asList(Keys.RECETA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RecetaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RecetaRecord, ?>>asList(Keys.RECETA__FK_RECETA_UNIDAD_MEDIDA_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Receta as(String alias) {
        return new Receta(alias, this);
    }

    /**
     * Rename this table
     */
    public Receta rename(String name) {
        return new Receta(name, null);
    }
}
