/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.VDetalleRecetaRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDetalleReceta extends TableImpl<VDetalleRecetaRecord> {

    private static final long serialVersionUID = 702364889;

    /**
     * The reference instance of <code>public.v_detalle_receta</code>
     */
    public static final VDetalleReceta V_DETALLE_RECETA = new VDetalleReceta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VDetalleRecetaRecord> getRecordType() {
        return VDetalleRecetaRecord.class;
    }

    /**
     * The column <code>public.v_detalle_receta.idreceta</code>.
     */
    public final TableField<VDetalleRecetaRecord, Integer> IDRECETA = createField("idreceta", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_receta.nombre</code>.
     */
    public final TableField<VDetalleRecetaRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_receta.idingrediente</code>.
     */
    public final TableField<VDetalleRecetaRecord, Integer> IDINGREDIENTE = createField("idingrediente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_receta.ingrediente</code>.
     */
    public final TableField<VDetalleRecetaRecord, String> INGREDIENTE = createField("ingrediente", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_receta.descargo</code>.
     */
    public final TableField<VDetalleRecetaRecord, Double> DESCARGO = createField("descargo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_detalle_receta.idunidad</code>.
     */
    public final TableField<VDetalleRecetaRecord, Integer> IDUNIDAD = createField("idunidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_receta.detalle</code>.
     */
    public final TableField<VDetalleRecetaRecord, String> DETALLE = createField("detalle", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_detalle_receta.costo</code>.
     */
    public final TableField<VDetalleRecetaRecord, BigDecimal> COSTO = createField("costo", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_detalle_receta.tipo</code>.
     */
    public final TableField<VDetalleRecetaRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_detalle_receta</code> table reference
     */
    public VDetalleReceta() {
        this("v_detalle_receta", null);
    }

    /**
     * Create an aliased <code>public.v_detalle_receta</code> table reference
     */
    public VDetalleReceta(String alias) {
        this(alias, V_DETALLE_RECETA);
    }

    private VDetalleReceta(String alias, Table<VDetalleRecetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private VDetalleReceta(String alias, Table<VDetalleRecetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleReceta as(String alias) {
        return new VDetalleReceta(alias, this);
    }

    /**
     * Rename this table
     */
    public VDetalleReceta rename(String name) {
        return new VDetalleReceta(name, null);
    }
}
