/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.VDetalleVentaRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDetalleVenta extends TableImpl<VDetalleVentaRecord> {

    private static final long serialVersionUID = -958286116;

    /**
     * The reference instance of <code>public.v_detalle_venta</code>
     */
    public static final VDetalleVenta V_DETALLE_VENTA = new VDetalleVenta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VDetalleVentaRecord> getRecordType() {
        return VDetalleVentaRecord.class;
    }

    /**
     * The column <code>public.v_detalle_venta.idventa</code>.
     */
    public final TableField<VDetalleVentaRecord, Integer> IDVENTA = createField("idventa", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_venta.idproducto</code>.
     */
    public final TableField<VDetalleVentaRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_venta.producto</code>.
     */
    public final TableField<VDetalleVentaRecord, String> PRODUCTO = createField("producto", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_venta.tipoproducto</code>.
     */
    public final TableField<VDetalleVentaRecord, String> TIPOPRODUCTO = createField("tipoproducto", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_venta.cantidad</code>.
     */
    public final TableField<VDetalleVentaRecord, Integer> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_venta.precio</code>.
     */
    public final TableField<VDetalleVentaRecord, BigDecimal> PRECIO = createField("precio", org.jooq.impl.SQLDataType.NUMERIC.precision(8, 4), this, "");

    /**
     * The column <code>public.v_detalle_venta.subtotal</code>.
     */
    public final TableField<VDetalleVentaRecord, BigDecimal> SUBTOTAL = createField("subtotal", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_detalle_venta.tipoventa</code>.
     */
    public final TableField<VDetalleVentaRecord, String> TIPOVENTA = createField("tipoventa", org.jooq.impl.SQLDataType.VARCHAR.length(2), this, "");

    /**
     * Create a <code>public.v_detalle_venta</code> table reference
     */
    public VDetalleVenta() {
        this("v_detalle_venta", null);
    }

    /**
     * Create an aliased <code>public.v_detalle_venta</code> table reference
     */
    public VDetalleVenta(String alias) {
        this(alias, V_DETALLE_VENTA);
    }

    private VDetalleVenta(String alias, Table<VDetalleVentaRecord> aliased) {
        this(alias, aliased, null);
    }

    private VDetalleVenta(String alias, Table<VDetalleVentaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleVenta as(String alias) {
        return new VDetalleVenta(alias, this);
    }

    /**
     * Rename this table
     */
    public VDetalleVenta rename(String name) {
        return new VDetalleVenta(name, null);
    }
}
