/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.VEmpleadosRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VEmpleados extends TableImpl<VEmpleadosRecord> {

    private static final long serialVersionUID = 235950306;

    /**
     * The reference instance of <code>public.v_empleados</code>
     */
    public static final VEmpleados V_EMPLEADOS = new VEmpleados();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VEmpleadosRecord> getRecordType() {
        return VEmpleadosRecord.class;
    }

    /**
     * The column <code>public.v_empleados.idempleado</code>.
     */
    public final TableField<VEmpleadosRecord, Integer> IDEMPLEADO = createField("idempleado", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_empleados.nombre</code>.
     */
    public final TableField<VEmpleadosRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.direccion</code>.
     */
    public final TableField<VEmpleadosRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.telefono</code>.
     */
    public final TableField<VEmpleadosRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.email</code>.
     */
    public final TableField<VEmpleadosRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.dui</code>.
     */
    public final TableField<VEmpleadosRecord, String> DUI = createField("dui", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.nit</code>.
     */
    public final TableField<VEmpleadosRecord, String> NIT = createField("nit", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.idpuesto</code>.
     */
    public final TableField<VEmpleadosRecord, Integer> IDPUESTO = createField("idpuesto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_empleados.puesto</code>.
     */
    public final TableField<VEmpleadosRecord, String> PUESTO = createField("puesto", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_empleados.salariodia</code>.
     */
    public final TableField<VEmpleadosRecord, BigDecimal> SALARIODIA = createField("salariodia", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_empleados.diaslaborales</code>.
     */
    public final TableField<VEmpleadosRecord, Integer> DIASLABORALES = createField("diaslaborales", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_empleados.salario_mensual</code>.
     */
    public final TableField<VEmpleadosRecord, BigDecimal> SALARIO_MENSUAL = createField("salario_mensual", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_empleados.manodeobra</code>.
     */
    public final TableField<VEmpleadosRecord, Boolean> MANODEOBRA = createField("manodeobra", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_empleados.baja</code>.
     */
    public final TableField<VEmpleadosRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.v_empleados</code> table reference
     */
    public VEmpleados() {
        this("v_empleados", null);
    }

    /**
     * Create an aliased <code>public.v_empleados</code> table reference
     */
    public VEmpleados(String alias) {
        this(alias, V_EMPLEADOS);
    }

    private VEmpleados(String alias, Table<VEmpleadosRecord> aliased) {
        this(alias, aliased, null);
    }

    private VEmpleados(String alias, Table<VEmpleadosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleados as(String alias) {
        return new VEmpleados(alias, this);
    }

    /**
     * Rename this table
     */
    public VEmpleados rename(String name) {
        return new VEmpleados(name, null);
    }
}
