/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.VIngredientesRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VIngredientes extends TableImpl<VIngredientesRecord> {

    private static final long serialVersionUID = -874661080;

    /**
     * The reference instance of <code>public.v_ingredientes</code>
     */
    public static final VIngredientes V_INGREDIENTES = new VIngredientes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VIngredientesRecord> getRecordType() {
        return VIngredientesRecord.class;
    }

    /**
     * The column <code>public.v_ingredientes.idingrediente</code>.
     */
    public final TableField<VIngredientesRecord, Integer> IDINGREDIENTE = createField("idingrediente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_ingredientes.ingrediente</code>.
     */
    public final TableField<VIngredientesRecord, String> INGREDIENTE = createField("ingrediente", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ingredientes.costo</code>.
     */
    public final TableField<VIngredientesRecord, BigDecimal> COSTO = createField("costo", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_ingredientes.stock</code>.
     */
    public final TableField<VIngredientesRecord, Double> STOCK = createField("stock", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_ingredientes.maximo</code>.
     */
    public final TableField<VIngredientesRecord, Double> MAXIMO = createField("maximo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_ingredientes.minimo</code>.
     */
    public final TableField<VIngredientesRecord, Double> MINIMO = createField("minimo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_ingredientes.idunidad</code>.
     */
    public final TableField<VIngredientesRecord, Integer> IDUNIDAD = createField("idunidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_ingredientes.unidad</code>.
     */
    public final TableField<VIngredientesRecord, String> UNIDAD = createField("unidad", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_ingredientes.tipo</code>.
     */
    public final TableField<VIngredientesRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ingredientes.baja</code>.
     */
    public final TableField<VIngredientesRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.v_ingredientes</code> table reference
     */
    public VIngredientes() {
        this("v_ingredientes", null);
    }

    /**
     * Create an aliased <code>public.v_ingredientes</code> table reference
     */
    public VIngredientes(String alias) {
        this(alias, V_INGREDIENTES);
    }

    private VIngredientes(String alias, Table<VIngredientesRecord> aliased) {
        this(alias, aliased, null);
    }

    private VIngredientes(String alias, Table<VIngredientesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientes as(String alias) {
        return new VIngredientes(alias, this);
    }

    /**
     * Rename this table
     */
    public VIngredientes rename(String name) {
        return new VIngredientes(name, null);
    }
}
