/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.VInsumosRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VInsumos extends TableImpl<VInsumosRecord> {

    private static final long serialVersionUID = -571165957;

    /**
     * The reference instance of <code>public.v_insumos</code>
     */
    public static final VInsumos V_INSUMOS = new VInsumos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VInsumosRecord> getRecordType() {
        return VInsumosRecord.class;
    }

    /**
     * The column <code>public.v_insumos.idinsumo</code>.
     */
    public final TableField<VInsumosRecord, Integer> IDINSUMO = createField("idinsumo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_insumos.nombre</code>.
     */
    public final TableField<VInsumosRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_insumos.costo</code>.
     */
    public final TableField<VInsumosRecord, BigDecimal> COSTO = createField("costo", org.jooq.impl.SQLDataType.NUMERIC.precision(7, 4), this, "");

    /**
     * The column <code>public.v_insumos.minimo</code>.
     */
    public final TableField<VInsumosRecord, Double> MINIMO = createField("minimo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_insumos.maximo</code>.
     */
    public final TableField<VInsumosRecord, Double> MAXIMO = createField("maximo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_insumos.stock</code>.
     */
    public final TableField<VInsumosRecord, Double> STOCK = createField("stock", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_insumos.unidad</code>.
     */
    public final TableField<VInsumosRecord, String> UNIDAD = createField("unidad", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_insumos.medida</code>.
     */
    public final TableField<VInsumosRecord, String> MEDIDA = createField("medida", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_insumos.baja</code>.
     */
    public final TableField<VInsumosRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_insumos.produccion</code>.
     */
    public final TableField<VInsumosRecord, Boolean> PRODUCCION = createField("produccion", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.v_insumos</code> table reference
     */
    public VInsumos() {
        this("v_insumos", null);
    }

    /**
     * Create an aliased <code>public.v_insumos</code> table reference
     */
    public VInsumos(String alias) {
        this(alias, V_INSUMOS);
    }

    private VInsumos(String alias, Table<VInsumosRecord> aliased) {
        this(alias, aliased, null);
    }

    private VInsumos(String alias, Table<VInsumosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumos as(String alias) {
        return new VInsumos(alias, this);
    }

    /**
     * Rename this table
     */
    public VInsumos rename(String name) {
        return new VInsumos(name, null);
    }
}
