/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database;


import com.pereira.manolos.datos.database.tables.BitacoraCaja;
import com.pereira.manolos.datos.database.tables.Caja;
import com.pereira.manolos.datos.database.tables.CategoriaProducto;
import com.pereira.manolos.datos.database.tables.Cliente;
import com.pereira.manolos.datos.database.tables.ClienteCreditofiscal;
import com.pereira.manolos.datos.database.tables.Compra;
import com.pereira.manolos.datos.database.tables.CostosIndirectos;
import com.pereira.manolos.datos.database.tables.Cotizacion;
import com.pereira.manolos.datos.database.tables.DetalleCompra;
import com.pereira.manolos.datos.database.tables.DetalleCotizacion;
import com.pereira.manolos.datos.database.tables.DetallePromocion;
import com.pereira.manolos.datos.database.tables.DetalleReceta;
import com.pereira.manolos.datos.database.tables.DetalleVenta;
import com.pereira.manolos.datos.database.tables.Empleado;
import com.pereira.manolos.datos.database.tables.Empresa;
import com.pereira.manolos.datos.database.tables.Insumo;
import com.pereira.manolos.datos.database.tables.Medida;
import com.pereira.manolos.datos.database.tables.Modulo;
import com.pereira.manolos.datos.database.tables.MovimientoCaja;
import com.pereira.manolos.datos.database.tables.PagosCompra;
import com.pereira.manolos.datos.database.tables.Permisos;
import com.pereira.manolos.datos.database.tables.Producto;
import com.pereira.manolos.datos.database.tables.Promocion;
import com.pereira.manolos.datos.database.tables.Proveedor;
import com.pereira.manolos.datos.database.tables.Puesto;
import com.pereira.manolos.datos.database.tables.Receta;
import com.pereira.manolos.datos.database.tables.Resolucion;
import com.pereira.manolos.datos.database.tables.UnidadMedida;
import com.pereira.manolos.datos.database.tables.Usuario;
import com.pereira.manolos.datos.database.tables.VAsociadoReceta;
import com.pereira.manolos.datos.database.tables.VCajaMovimiento;
import com.pereira.manolos.datos.database.tables.VCif;
import com.pereira.manolos.datos.database.tables.VCompras;
import com.pereira.manolos.datos.database.tables.VCotizacion;
import com.pereira.manolos.datos.database.tables.VDetalleCompra;
import com.pereira.manolos.datos.database.tables.VDetalleCotizacion;
import com.pereira.manolos.datos.database.tables.VDetalleReceta;
import com.pereira.manolos.datos.database.tables.VDetalleVenta;
import com.pereira.manolos.datos.database.tables.VEmpleados;
import com.pereira.manolos.datos.database.tables.VIngredientes;
import com.pereira.manolos.datos.database.tables.VInsumos;
import com.pereira.manolos.datos.database.tables.VMedidas;
import com.pereira.manolos.datos.database.tables.VModHora;
import com.pereira.manolos.datos.database.tables.VRecetas;
import com.pereira.manolos.datos.database.tables.VVenta;
import com.pereira.manolos.datos.database.tables.Venta;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -204163236;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.bitacora_caja</code>.
     */
    public final BitacoraCaja BITACORA_CAJA = com.pereira.manolos.datos.database.tables.BitacoraCaja.BITACORA_CAJA;

    /**
     * The table <code>public.caja</code>.
     */
    public final Caja CAJA = com.pereira.manolos.datos.database.tables.Caja.CAJA;

    /**
     * The table <code>public.categoria_producto</code>.
     */
    public final CategoriaProducto CATEGORIA_PRODUCTO = com.pereira.manolos.datos.database.tables.CategoriaProducto.CATEGORIA_PRODUCTO;

    /**
     * The table <code>public.cliente</code>.
     */
    public final Cliente CLIENTE = com.pereira.manolos.datos.database.tables.Cliente.CLIENTE;

    /**
     * The table <code>public.cliente_creditofiscal</code>.
     */
    public final ClienteCreditofiscal CLIENTE_CREDITOFISCAL = com.pereira.manolos.datos.database.tables.ClienteCreditofiscal.CLIENTE_CREDITOFISCAL;

    /**
     * The table <code>public.compra</code>.
     */
    public final Compra COMPRA = com.pereira.manolos.datos.database.tables.Compra.COMPRA;

    /**
     * The table <code>public.costos_indirectos</code>.
     */
    public final CostosIndirectos COSTOS_INDIRECTOS = com.pereira.manolos.datos.database.tables.CostosIndirectos.COSTOS_INDIRECTOS;

    /**
     * The table <code>public.cotizacion</code>.
     */
    public final Cotizacion COTIZACION = com.pereira.manolos.datos.database.tables.Cotizacion.COTIZACION;

    /**
     * The table <code>public.detalle_compra</code>.
     */
    public final DetalleCompra DETALLE_COMPRA = com.pereira.manolos.datos.database.tables.DetalleCompra.DETALLE_COMPRA;

    /**
     * The table <code>public.detalle_cotizacion</code>.
     */
    public final DetalleCotizacion DETALLE_COTIZACION = com.pereira.manolos.datos.database.tables.DetalleCotizacion.DETALLE_COTIZACION;

    /**
     * The table <code>public.detalle_promocion</code>.
     */
    public final DetallePromocion DETALLE_PROMOCION = com.pereira.manolos.datos.database.tables.DetallePromocion.DETALLE_PROMOCION;

    /**
     * The table <code>public.detalle_receta</code>.
     */
    public final DetalleReceta DETALLE_RECETA = com.pereira.manolos.datos.database.tables.DetalleReceta.DETALLE_RECETA;

    /**
     * The table <code>public.detalle_venta</code>.
     */
    public final DetalleVenta DETALLE_VENTA = com.pereira.manolos.datos.database.tables.DetalleVenta.DETALLE_VENTA;

    /**
     * The table <code>public.empleado</code>.
     */
    public final Empleado EMPLEADO = com.pereira.manolos.datos.database.tables.Empleado.EMPLEADO;

    /**
     * The table <code>public.empresa</code>.
     */
    public final Empresa EMPRESA = com.pereira.manolos.datos.database.tables.Empresa.EMPRESA;

    /**
     * The table <code>public.insumo</code>.
     */
    public final Insumo INSUMO = com.pereira.manolos.datos.database.tables.Insumo.INSUMO;

    /**
     * The table <code>public.medida</code>.
     */
    public final Medida MEDIDA = com.pereira.manolos.datos.database.tables.Medida.MEDIDA;

    /**
     * The table <code>public.modulo</code>.
     */
    public final Modulo MODULO = com.pereira.manolos.datos.database.tables.Modulo.MODULO;

    /**
     * The table <code>public.movimiento_caja</code>.
     */
    public final MovimientoCaja MOVIMIENTO_CAJA = com.pereira.manolos.datos.database.tables.MovimientoCaja.MOVIMIENTO_CAJA;

    /**
     * The table <code>public.pagos_compra</code>.
     */
    public final PagosCompra PAGOS_COMPRA = com.pereira.manolos.datos.database.tables.PagosCompra.PAGOS_COMPRA;

    /**
     * The table <code>public.permisos</code>.
     */
    public final Permisos PERMISOS = com.pereira.manolos.datos.database.tables.Permisos.PERMISOS;

    /**
     * The table <code>public.producto</code>.
     */
    public final Producto PRODUCTO = com.pereira.manolos.datos.database.tables.Producto.PRODUCTO;

    /**
     * The table <code>public.promocion</code>.
     */
    public final Promocion PROMOCION = com.pereira.manolos.datos.database.tables.Promocion.PROMOCION;

    /**
     * The table <code>public.proveedor</code>.
     */
    public final Proveedor PROVEEDOR = com.pereira.manolos.datos.database.tables.Proveedor.PROVEEDOR;

    /**
     * The table <code>public.puesto</code>.
     */
    public final Puesto PUESTO = com.pereira.manolos.datos.database.tables.Puesto.PUESTO;

    /**
     * The table <code>public.receta</code>.
     */
    public final Receta RECETA = com.pereira.manolos.datos.database.tables.Receta.RECETA;

    /**
     * The table <code>public.resolucion</code>.
     */
    public final Resolucion RESOLUCION = com.pereira.manolos.datos.database.tables.Resolucion.RESOLUCION;

    /**
     * The table <code>public.unidad_medida</code>.
     */
    public final UnidadMedida UNIDAD_MEDIDA = com.pereira.manolos.datos.database.tables.UnidadMedida.UNIDAD_MEDIDA;

    /**
     * The table <code>public.usuario</code>.
     */
    public final Usuario USUARIO = com.pereira.manolos.datos.database.tables.Usuario.USUARIO;

    /**
     * The table <code>public.v_asociado_receta</code>.
     */
    public final VAsociadoReceta V_ASOCIADO_RECETA = com.pereira.manolos.datos.database.tables.VAsociadoReceta.V_ASOCIADO_RECETA;

    /**
     * The table <code>public.v_caja_movimiento</code>.
     */
    public final VCajaMovimiento V_CAJA_MOVIMIENTO = com.pereira.manolos.datos.database.tables.VCajaMovimiento.V_CAJA_MOVIMIENTO;

    /**
     * The table <code>public.v_cif</code>.
     */
    public final VCif V_CIF = com.pereira.manolos.datos.database.tables.VCif.V_CIF;

    /**
     * The table <code>public.v_compras</code>.
     */
    public final VCompras V_COMPRAS = com.pereira.manolos.datos.database.tables.VCompras.V_COMPRAS;

    /**
     * The table <code>public.v_cotizacion</code>.
     */
    public final VCotizacion V_COTIZACION = com.pereira.manolos.datos.database.tables.VCotizacion.V_COTIZACION;

    /**
     * The table <code>public.v_detalle_compra</code>.
     */
    public final VDetalleCompra V_DETALLE_COMPRA = com.pereira.manolos.datos.database.tables.VDetalleCompra.V_DETALLE_COMPRA;

    /**
     * The table <code>public.v_detalle_cotizacion</code>.
     */
    public final VDetalleCotizacion V_DETALLE_COTIZACION = com.pereira.manolos.datos.database.tables.VDetalleCotizacion.V_DETALLE_COTIZACION;

    /**
     * The table <code>public.v_detalle_receta</code>.
     */
    public final VDetalleReceta V_DETALLE_RECETA = com.pereira.manolos.datos.database.tables.VDetalleReceta.V_DETALLE_RECETA;

    /**
     * The table <code>public.v_detalle_venta</code>.
     */
    public final VDetalleVenta V_DETALLE_VENTA = com.pereira.manolos.datos.database.tables.VDetalleVenta.V_DETALLE_VENTA;

    /**
     * The table <code>public.v_empleados</code>.
     */
    public final VEmpleados V_EMPLEADOS = com.pereira.manolos.datos.database.tables.VEmpleados.V_EMPLEADOS;

    /**
     * The table <code>public.v_ingredientes</code>.
     */
    public final VIngredientes V_INGREDIENTES = com.pereira.manolos.datos.database.tables.VIngredientes.V_INGREDIENTES;

    /**
     * The table <code>public.v_insumos</code>.
     */
    public final VInsumos V_INSUMOS = com.pereira.manolos.datos.database.tables.VInsumos.V_INSUMOS;

    /**
     * The table <code>public.v_medidas</code>.
     */
    public final VMedidas V_MEDIDAS = com.pereira.manolos.datos.database.tables.VMedidas.V_MEDIDAS;

    /**
     * The table <code>public.v_mod_hora</code>.
     */
    public final VModHora V_MOD_HORA = com.pereira.manolos.datos.database.tables.VModHora.V_MOD_HORA;

    /**
     * The table <code>public.v_recetas</code>.
     */
    public final VRecetas V_RECETAS = com.pereira.manolos.datos.database.tables.VRecetas.V_RECETAS;

    /**
     * The table <code>public.v_venta</code>.
     */
    public final VVenta V_VENTA = com.pereira.manolos.datos.database.tables.VVenta.V_VENTA;

    /**
     * The table <code>public.venta</code>.
     */
    public final Venta VENTA = com.pereira.manolos.datos.database.tables.Venta.VENTA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CAJA_IDCAJA_SEQ,
            Sequences.CATEGORIA_PRODUCTO_IDCATEGORIA_SEQ,
            Sequences.CLIENTE_IDCLIENTE_SEQ,
            Sequences.COMPRA_IDCOMPRA_SEQ,
            Sequences.COSTOS_INDIRECTOS_IDCOSTOS_SEQ,
            Sequences.COTIZACION_IDCOTIZACION_SEQ,
            Sequences.EMPLEADO_IDEMPLEADO_SEQ,
            Sequences.INSUMO_IDINSUMO_SEQ,
            Sequences.PRODUCTO_IDPRODUCTO_SEQ,
            Sequences.PROMOCION_IDPROMOCION_SEQ,
            Sequences.PROVEEDOR_IDPROVEEDOR_SEQ,
            Sequences.PUESTO_IDPUESTO_SEQ,
            Sequences.RECETA_IDRECETA_SEQ,
            Sequences.RESOLUCION_IDRESOLUCION_SEQ,
            Sequences.USUARIO_IDUSUARIO_SEQ,
            Sequences.VENTA_IDVENTA_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BitacoraCaja.BITACORA_CAJA,
            Caja.CAJA,
            CategoriaProducto.CATEGORIA_PRODUCTO,
            Cliente.CLIENTE,
            ClienteCreditofiscal.CLIENTE_CREDITOFISCAL,
            Compra.COMPRA,
            CostosIndirectos.COSTOS_INDIRECTOS,
            Cotizacion.COTIZACION,
            DetalleCompra.DETALLE_COMPRA,
            DetalleCotizacion.DETALLE_COTIZACION,
            DetallePromocion.DETALLE_PROMOCION,
            DetalleReceta.DETALLE_RECETA,
            DetalleVenta.DETALLE_VENTA,
            Empleado.EMPLEADO,
            Empresa.EMPRESA,
            Insumo.INSUMO,
            Medida.MEDIDA,
            Modulo.MODULO,
            MovimientoCaja.MOVIMIENTO_CAJA,
            PagosCompra.PAGOS_COMPRA,
            Permisos.PERMISOS,
            Producto.PRODUCTO,
            Promocion.PROMOCION,
            Proveedor.PROVEEDOR,
            Puesto.PUESTO,
            Receta.RECETA,
            Resolucion.RESOLUCION,
            UnidadMedida.UNIDAD_MEDIDA,
            Usuario.USUARIO,
            VAsociadoReceta.V_ASOCIADO_RECETA,
            VCajaMovimiento.V_CAJA_MOVIMIENTO,
            VCif.V_CIF,
            VCompras.V_COMPRAS,
            VCotizacion.V_COTIZACION,
            VDetalleCompra.V_DETALLE_COMPRA,
            VDetalleCotizacion.V_DETALLE_COTIZACION,
            VDetalleReceta.V_DETALLE_RECETA,
            VDetalleVenta.V_DETALLE_VENTA,
            VEmpleados.V_EMPLEADOS,
            VIngredientes.V_INGREDIENTES,
            VInsumos.V_INSUMOS,
            VMedidas.V_MEDIDAS,
            VModHora.V_MOD_HORA,
            VRecetas.V_RECETAS,
            VVenta.V_VENTA,
            Venta.VENTA);
    }
}
