/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.caja_idcaja_seq</code>
     */
    public static final Sequence<Long> CAJA_IDCAJA_SEQ = new SequenceImpl<Long>("caja_idcaja_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.categoria_producto_idcategoria_seq</code>
     */
    public static final Sequence<Long> CATEGORIA_PRODUCTO_IDCATEGORIA_SEQ = new SequenceImpl<Long>("categoria_producto_idcategoria_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.cliente_idcliente_seq</code>
     */
    public static final Sequence<Long> CLIENTE_IDCLIENTE_SEQ = new SequenceImpl<Long>("cliente_idcliente_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.compra_idcompra_seq</code>
     */
    public static final Sequence<Long> COMPRA_IDCOMPRA_SEQ = new SequenceImpl<Long>("compra_idcompra_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.costos_indirectos_idcostos_seq</code>
     */
    public static final Sequence<Long> COSTOS_INDIRECTOS_IDCOSTOS_SEQ = new SequenceImpl<Long>("costos_indirectos_idcostos_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.cotizacion_idcotizacion_seq</code>
     */
    public static final Sequence<Long> COTIZACION_IDCOTIZACION_SEQ = new SequenceImpl<Long>("cotizacion_idcotizacion_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.empleado_idempleado_seq</code>
     */
    public static final Sequence<Long> EMPLEADO_IDEMPLEADO_SEQ = new SequenceImpl<Long>("empleado_idempleado_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.insumo_idinsumo_seq</code>
     */
    public static final Sequence<Long> INSUMO_IDINSUMO_SEQ = new SequenceImpl<Long>("insumo_idinsumo_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.producto_idproducto_seq</code>
     */
    public static final Sequence<Long> PRODUCTO_IDPRODUCTO_SEQ = new SequenceImpl<Long>("producto_idproducto_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.promocion_idpromocion_seq</code>
     */
    public static final Sequence<Long> PROMOCION_IDPROMOCION_SEQ = new SequenceImpl<Long>("promocion_idpromocion_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.proveedor_idproveedor_seq</code>
     */
    public static final Sequence<Long> PROVEEDOR_IDPROVEEDOR_SEQ = new SequenceImpl<Long>("proveedor_idproveedor_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.puesto_idpuesto_seq</code>
     */
    public static final Sequence<Long> PUESTO_IDPUESTO_SEQ = new SequenceImpl<Long>("puesto_idpuesto_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.receta_idreceta_seq</code>
     */
    public static final Sequence<Long> RECETA_IDRECETA_SEQ = new SequenceImpl<Long>("receta_idreceta_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.resolucion_idresolucion_seq</code>
     */
    public static final Sequence<Long> RESOLUCION_IDRESOLUCION_SEQ = new SequenceImpl<Long>("resolucion_idresolucion_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.usuario_idusuario_seq</code>
     */
    public static final Sequence<Long> USUARIO_IDUSUARIO_SEQ = new SequenceImpl<Long>("usuario_idusuario_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.venta_idventa_seq</code>
     */
    public static final Sequence<Long> VENTA_IDVENTA_SEQ = new SequenceImpl<Long>("venta_idventa_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
