/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.CostosIndirectos;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CostosIndirectosRecord extends UpdatableRecordImpl<CostosIndirectosRecord> implements Record3<Integer, String, BigDecimal> {

    private static final long serialVersionUID = 2108015831;

    /**
     * Setter for <code>public.costos_indirectos.idcosto</code>.
     */
    public void setIdcosto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.costos_indirectos.idcosto</code>.
     */
    public Integer getIdcosto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.costos_indirectos.rubro</code>.
     */
    public void setRubro(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.costos_indirectos.rubro</code>.
     */
    public String getRubro() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.costos_indirectos.valor</code>.
     */
    public void setValor(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.costos_indirectos.valor</code>.
     */
    public BigDecimal getValor() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CostosIndirectos.COSTOS_INDIRECTOS.IDCOSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CostosIndirectos.COSTOS_INDIRECTOS.RUBRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return CostosIndirectos.COSTOS_INDIRECTOS.VALOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRubro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getValor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostosIndirectosRecord value1(Integer value) {
        setIdcosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostosIndirectosRecord value2(String value) {
        setRubro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostosIndirectosRecord value3(BigDecimal value) {
        setValor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostosIndirectosRecord values(Integer value1, String value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CostosIndirectosRecord
     */
    public CostosIndirectosRecord() {
        super(CostosIndirectos.COSTOS_INDIRECTOS);
    }

    /**
     * Create a detached, initialised CostosIndirectosRecord
     */
    public CostosIndirectosRecord(Integer idcosto, String rubro, BigDecimal valor) {
        super(CostosIndirectos.COSTOS_INDIRECTOS);

        set(0, idcosto);
        set(1, rubro);
        set(2, valor);
    }
}
