/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.DetalleReceta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleRecetaRecord extends TableRecordImpl<DetalleRecetaRecord> implements Record6<Integer, Integer, Double, Integer, String, Integer> {

    private static final long serialVersionUID = 318996959;

    /**
     * Setter for <code>public.detalle_receta.idreceta</code>.
     */
    public void setIdreceta(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.detalle_receta.idreceta</code>.
     */
    public Integer getIdreceta() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.detalle_receta.ingrediente</code>.
     */
    public void setIngrediente(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.detalle_receta.ingrediente</code>.
     */
    public Integer getIngrediente() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.detalle_receta.descargo</code>.
     */
    public void setDescargo(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.detalle_receta.descargo</code>.
     */
    public Double getDescargo() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.detalle_receta.idunidad</code>.
     */
    public void setIdunidad(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.detalle_receta.idunidad</code>.
     */
    public Integer getIdunidad() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.detalle_receta.tipo</code>.
     */
    public void setTipo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.detalle_receta.tipo</code>.
     */
    public String getTipo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.detalle_receta.ingredientereceta</code>.
     */
    public void setIngredientereceta(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.detalle_receta.ingredientereceta</code>.
     */
    public Integer getIngredientereceta() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Double, Integer, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Double, Integer, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DetalleReceta.DETALLE_RECETA.IDRECETA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DetalleReceta.DETALLE_RECETA.INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return DetalleReceta.DETALLE_RECETA.DESCARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DetalleReceta.DETALLE_RECETA.IDUNIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DetalleReceta.DETALLE_RECETA.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return DetalleReceta.DETALLE_RECETA.INGREDIENTERECETA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdreceta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIngrediente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getDescargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdunidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIngredientereceta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord value1(Integer value) {
        setIdreceta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord value2(Integer value) {
        setIngrediente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord value3(Double value) {
        setDescargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord value4(Integer value) {
        setIdunidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord value5(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord value6(Integer value) {
        setIngredientereceta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleRecetaRecord values(Integer value1, Integer value2, Double value3, Integer value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DetalleRecetaRecord
     */
    public DetalleRecetaRecord() {
        super(DetalleReceta.DETALLE_RECETA);
    }

    /**
     * Create a detached, initialised DetalleRecetaRecord
     */
    public DetalleRecetaRecord(Integer idreceta, Integer ingrediente, Double descargo, Integer idunidad, String tipo, Integer ingredientereceta) {
        super(DetalleReceta.DETALLE_RECETA);

        set(0, idreceta);
        set(1, ingrediente);
        set(2, descargo);
        set(3, idunidad);
        set(4, tipo);
        set(5, ingredientereceta);
    }
}
