/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Empresa;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmpresaRecord extends UpdatableRecordImpl<EmpresaRecord> implements Record13<String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, Integer, byte[], Integer> {

    private static final long serialVersionUID = -1864519398;

    /**
     * Setter for <code>public.empresa.nombre</code>.
     */
    public void setNombre(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.empresa.nombre</code>.
     */
    public String getNombre() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.empresa.direccion</code>.
     */
    public void setDireccion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.empresa.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.empresa.telefono</code>.
     */
    public void setTelefono(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.empresa.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.empresa.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.empresa.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.empresa.propietario</code>.
     */
    public void setPropietario(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.empresa.propietario</code>.
     */
    public String getPropietario() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.empresa.giro</code>.
     */
    public void setGiro(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.empresa.giro</code>.
     */
    public String getGiro() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.empresa.nrc</code>.
     */
    public void setNrc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.empresa.nrc</code>.
     */
    public String getNrc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.empresa.nit</code>.
     */
    public void setNit(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.empresa.nit</code>.
     */
    public String getNit() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.empresa.iva</code>.
     */
    public void setIva(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.empresa.iva</code>.
     */
    public BigDecimal getIva() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.empresa.conversion</code>.
     */
    public void setConversion(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.empresa.conversion</code>.
     */
    public BigDecimal getConversion() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.empresa.horastrabajo</code>.
     */
    public void setHorastrabajo(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.empresa.horastrabajo</code>.
     */
    public Integer getHorastrabajo() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.empresa.logo</code>.
     */
    public void setLogo(byte[] value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.empresa.logo</code>.
     */
    public byte[] getLogo() {
        return (byte[]) get(11);
    }

    /**
     * Setter for <code>public.empresa.idempresa</code>.
     */
    public void setIdempresa(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.empresa.idempresa</code>.
     */
    public Integer getIdempresa() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, Integer, byte[], Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, Integer, byte[], Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Empresa.EMPRESA.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Empresa.EMPRESA.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Empresa.EMPRESA.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Empresa.EMPRESA.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Empresa.EMPRESA.PROPIETARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Empresa.EMPRESA.GIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Empresa.EMPRESA.NRC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Empresa.EMPRESA.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Empresa.EMPRESA.IVA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return Empresa.EMPRESA.CONVERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Empresa.EMPRESA.HORASTRABAJO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field12() {
        return Empresa.EMPRESA.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Empresa.EMPRESA.IDEMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPropietario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGiro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNrc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getIva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getConversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getHorastrabajo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value12() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value1(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value2(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value3(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value5(String value) {
        setPropietario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value6(String value) {
        setGiro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value7(String value) {
        setNrc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value8(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value9(BigDecimal value) {
        setIva(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value10(BigDecimal value) {
        setConversion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value11(Integer value) {
        setHorastrabajo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value12(byte[] value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord value13(Integer value) {
        setIdempresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpresaRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, BigDecimal value9, BigDecimal value10, Integer value11, byte[] value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmpresaRecord
     */
    public EmpresaRecord() {
        super(Empresa.EMPRESA);
    }

    /**
     * Create a detached, initialised EmpresaRecord
     */
    public EmpresaRecord(String nombre, String direccion, String telefono, String email, String propietario, String giro, String nrc, String nit, BigDecimal iva, BigDecimal conversion, Integer horastrabajo, byte[] logo, Integer idempresa) {
        super(Empresa.EMPRESA);

        set(0, nombre);
        set(1, direccion);
        set(2, telefono);
        set(3, email);
        set(4, propietario);
        set(5, giro);
        set(6, nrc);
        set(7, nit);
        set(8, iva);
        set(9, conversion);
        set(10, horastrabajo);
        set(11, logo);
        set(12, idempresa);
    }
}
