/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Promocion;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PromocionRecord extends UpdatableRecordImpl<PromocionRecord> implements Record13<Integer, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, BigDecimal, BigDecimal, String, String, byte[]> {

    private static final long serialVersionUID = 1893874352;

    /**
     * Setter for <code>public.promocion.idpromocion</code>.
     */
    public void setIdpromocion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.promocion.idpromocion</code>.
     */
    public Integer getIdpromocion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.promocion.lunes</code>.
     */
    public void setLunes(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.promocion.lunes</code>.
     */
    public Boolean getLunes() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.promocion.martes</code>.
     */
    public void setMartes(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.promocion.martes</code>.
     */
    public Boolean getMartes() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.promocion.miercoles</code>.
     */
    public void setMiercoles(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.promocion.miercoles</code>.
     */
    public Boolean getMiercoles() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.promocion.jueves</code>.
     */
    public void setJueves(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.promocion.jueves</code>.
     */
    public Boolean getJueves() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.promocion.viernes</code>.
     */
    public void setViernes(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.promocion.viernes</code>.
     */
    public Boolean getViernes() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.promocion.sabado</code>.
     */
    public void setSabado(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.promocion.sabado</code>.
     */
    public Boolean getSabado() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.promocion.domingo</code>.
     */
    public void setDomingo(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.promocion.domingo</code>.
     */
    public Boolean getDomingo() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.promocion.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.promocion.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.promocion.costo</code>.
     */
    public void setCosto(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.promocion.costo</code>.
     */
    public BigDecimal getCosto() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.promocion.nombre</code>.
     */
    public void setNombre(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.promocion.nombre</code>.
     */
    public String getNombre() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.promocion.tipoventa</code>.
     */
    public void setTipoventa(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.promocion.tipoventa</code>.
     */
    public String getTipoventa() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.promocion.imagen</code>.
     */
    public void setImagen(byte[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.promocion.imagen</code>.
     */
    public byte[] getImagen() {
        return (byte[]) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, BigDecimal, BigDecimal, String, String, byte[]> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, BigDecimal, BigDecimal, String, String, byte[]> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Promocion.PROMOCION.IDPROMOCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return Promocion.PROMOCION.LUNES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Promocion.PROMOCION.MARTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Promocion.PROMOCION.MIERCOLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Promocion.PROMOCION.JUEVES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Promocion.PROMOCION.VIERNES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Promocion.PROMOCION.SABADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Promocion.PROMOCION.DOMINGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Promocion.PROMOCION.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return Promocion.PROMOCION.COSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Promocion.PROMOCION.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Promocion.PROMOCION.TIPOVENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field13() {
        return Promocion.PROMOCION.IMAGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdpromocion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getLunes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getMartes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getMiercoles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getJueves();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getViernes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getSabado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getDomingo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTipoventa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value13() {
        return getImagen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value1(Integer value) {
        setIdpromocion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value2(Boolean value) {
        setLunes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value3(Boolean value) {
        setMartes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value4(Boolean value) {
        setMiercoles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value5(Boolean value) {
        setJueves(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value6(Boolean value) {
        setViernes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value7(Boolean value) {
        setSabado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value8(Boolean value) {
        setDomingo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value9(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value10(BigDecimal value) {
        setCosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value11(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value12(String value) {
        setTipoventa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord value13(byte[] value) {
        setImagen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromocionRecord values(Integer value1, Boolean value2, Boolean value3, Boolean value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, BigDecimal value9, BigDecimal value10, String value11, String value12, byte[] value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PromocionRecord
     */
    public PromocionRecord() {
        super(Promocion.PROMOCION);
    }

    /**
     * Create a detached, initialised PromocionRecord
     */
    public PromocionRecord(Integer idpromocion, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabado, Boolean domingo, BigDecimal precio, BigDecimal costo, String nombre, String tipoventa, byte[] imagen) {
        super(Promocion.PROMOCION);

        set(0, idpromocion);
        set(1, lunes);
        set(2, martes);
        set(3, miercoles);
        set(4, jueves);
        set(5, viernes);
        set(6, sabado);
        set(7, domingo);
        set(8, precio);
        set(9, costo);
        set(10, nombre);
        set(11, tipoventa);
        set(12, imagen);
    }
}
