/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Proveedor;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProveedorRecord extends UpdatableRecordImpl<ProveedorRecord> implements Record13<Integer, String, String, String, String, String, String, String, String, String, Integer, BigDecimal, Boolean> {

    private static final long serialVersionUID = -1136177736;

    /**
     * Setter for <code>public.proveedor.idproveedor</code>.
     */
    public void setIdproveedor(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.proveedor.idproveedor</code>.
     */
    public Integer getIdproveedor() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.proveedor.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.proveedor.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.proveedor.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.proveedor.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.proveedor.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.proveedor.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.proveedor.giro</code>.
     */
    public void setGiro(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.proveedor.giro</code>.
     */
    public String getGiro() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.proveedor.nit</code>.
     */
    public void setNit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.proveedor.nit</code>.
     */
    public String getNit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.proveedor.nrc</code>.
     */
    public void setNrc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.proveedor.nrc</code>.
     */
    public String getNrc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.proveedor.mail</code>.
     */
    public void setMail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.proveedor.mail</code>.
     */
    public String getMail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.proveedor.representante</code>.
     */
    public void setRepresentante(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.proveedor.representante</code>.
     */
    public String getRepresentante() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.proveedor.tipoproveedor</code>.
     */
    public void setTipoproveedor(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.proveedor.tipoproveedor</code>.
     */
    public String getTipoproveedor() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.proveedor.plazo</code>.
     */
    public void setPlazo(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.proveedor.plazo</code>.
     */
    public Integer getPlazo() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.proveedor.limite</code>.
     */
    public void setLimite(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.proveedor.limite</code>.
     */
    public BigDecimal getLimite() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.proveedor.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.proveedor.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, Integer, BigDecimal, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, Integer, BigDecimal, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Proveedor.PROVEEDOR.IDPROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Proveedor.PROVEEDOR.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Proveedor.PROVEEDOR.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Proveedor.PROVEEDOR.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Proveedor.PROVEEDOR.GIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Proveedor.PROVEEDOR.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Proveedor.PROVEEDOR.NRC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Proveedor.PROVEEDOR.MAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Proveedor.PROVEEDOR.REPRESENTANTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Proveedor.PROVEEDOR.TIPOPROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Proveedor.PROVEEDOR.PLAZO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return Proveedor.PROVEEDOR.LIMITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return Proveedor.PROVEEDOR.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdproveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getGiro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNrc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRepresentante();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTipoproveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getPlazo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getLimite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value1(Integer value) {
        setIdproveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value5(String value) {
        setGiro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value6(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value7(String value) {
        setNrc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value8(String value) {
        setMail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value9(String value) {
        setRepresentante(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value10(String value) {
        setTipoproveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value11(Integer value) {
        setPlazo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value12(BigDecimal value) {
        setLimite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value13(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Integer value11, BigDecimal value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProveedorRecord
     */
    public ProveedorRecord() {
        super(Proveedor.PROVEEDOR);
    }

    /**
     * Create a detached, initialised ProveedorRecord
     */
    public ProveedorRecord(Integer idproveedor, String nombre, String direccion, String telefono, String giro, String nit, String nrc, String mail, String representante, String tipoproveedor, Integer plazo, BigDecimal limite, Boolean baja) {
        super(Proveedor.PROVEEDOR);

        set(0, idproveedor);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, giro);
        set(5, nit);
        set(6, nrc);
        set(7, mail);
        set(8, representante);
        set(9, tipoproveedor);
        set(10, plazo);
        set(11, limite);
        set(12, baja);
    }
}
