/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Puesto;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PuestoRecord extends UpdatableRecordImpl<PuestoRecord> implements Record5<Integer, String, BigDecimal, Integer, Boolean> {

    private static final long serialVersionUID = 1438779620;

    /**
     * Setter for <code>public.puesto.idpuesto</code>.
     */
    public void setIdpuesto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.puesto.idpuesto</code>.
     */
    public Integer getIdpuesto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.puesto.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.puesto.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.puesto.salariodia</code>.
     */
    public void setSalariodia(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.puesto.salariodia</code>.
     */
    public BigDecimal getSalariodia() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.puesto.diaslaborales</code>.
     */
    public void setDiaslaborales(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.puesto.diaslaborales</code>.
     */
    public Integer getDiaslaborales() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.puesto.mod</code>.
     */
    public void setMod(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.puesto.mod</code>.
     */
    public Boolean getMod() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, BigDecimal, Integer, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, BigDecimal, Integer, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Puesto.PUESTO.IDPUESTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Puesto.PUESTO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Puesto.PUESTO.SALARIODIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Puesto.PUESTO.DIASLABORALES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Puesto.PUESTO.MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdpuesto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getSalariodia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDiaslaborales();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PuestoRecord value1(Integer value) {
        setIdpuesto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PuestoRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PuestoRecord value3(BigDecimal value) {
        setSalariodia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PuestoRecord value4(Integer value) {
        setDiaslaborales(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PuestoRecord value5(Boolean value) {
        setMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PuestoRecord values(Integer value1, String value2, BigDecimal value3, Integer value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PuestoRecord
     */
    public PuestoRecord() {
        super(Puesto.PUESTO);
    }

    /**
     * Create a detached, initialised PuestoRecord
     */
    public PuestoRecord(Integer idpuesto, String nombre, BigDecimal salariodia, Integer diaslaborales, Boolean mod) {
        super(Puesto.PUESTO);

        set(0, idpuesto);
        set(1, nombre);
        set(2, salariodia);
        set(3, diaslaborales);
        set(4, mod);
    }
}
