/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Resolucion;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResolucionRecord extends UpdatableRecordImpl<ResolucionRecord> implements Record10<Integer, String, Integer, Integer, Integer, Integer, String, Date, Integer, Boolean> {

    private static final long serialVersionUID = -1416709136;

    /**
     * Setter for <code>public.resolucion.idresolucion</code>.
     */
    public void setIdresolucion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.resolucion.idresolucion</code>.
     */
    public Integer getIdresolucion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.resolucion.resolucion</code>.
     */
    public void setResolucion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.resolucion.resolucion</code>.
     */
    public String getResolucion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.resolucion.tktinicial</code>.
     */
    public void setTktinicial(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.resolucion.tktinicial</code>.
     */
    public Integer getTktinicial() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.resolucion.tktfinal</code>.
     */
    public void setTktfinal(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.resolucion.tktfinal</code>.
     */
    public Integer getTktfinal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.resolucion.tktactual</code>.
     */
    public void setTktactual(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.resolucion.tktactual</code>.
     */
    public Integer getTktactual() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.resolucion.tktalerta</code>.
     */
    public void setTktalerta(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.resolucion.tktalerta</code>.
     */
    public Integer getTktalerta() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.resolucion.serie</code>.
     */
    public void setSerie(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.resolucion.serie</code>.
     */
    public String getSerie() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.resolucion.fecha</code>.
     */
    public void setFecha(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.resolucion.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>public.resolucion.idcaja</code>.
     */
    public void setIdcaja(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.resolucion.idcaja</code>.
     */
    public Integer getIdcaja() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.resolucion.activa</code>.
     */
    public void setActiva(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.resolucion.activa</code>.
     */
    public Boolean getActiva() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, Integer, Integer, Integer, String, Date, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, Integer, Integer, Integer, String, Date, Integer, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Resolucion.RESOLUCION.IDRESOLUCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Resolucion.RESOLUCION.RESOLUCION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Resolucion.RESOLUCION.TKTINICIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Resolucion.RESOLUCION.TKTFINAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Resolucion.RESOLUCION.TKTACTUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Resolucion.RESOLUCION.TKTALERTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Resolucion.RESOLUCION.SERIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Resolucion.RESOLUCION.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Resolucion.RESOLUCION.IDCAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Resolucion.RESOLUCION.ACTIVA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdresolucion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getResolucion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTktinicial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTktfinal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTktactual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTktalerta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSerie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdcaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getActiva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value1(Integer value) {
        setIdresolucion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value2(String value) {
        setResolucion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value3(Integer value) {
        setTktinicial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value4(Integer value) {
        setTktfinal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value5(Integer value) {
        setTktactual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value6(Integer value) {
        setTktalerta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value7(String value) {
        setSerie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value8(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value9(Integer value) {
        setIdcaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord value10(Boolean value) {
        setActiva(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResolucionRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7, Date value8, Integer value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResolucionRecord
     */
    public ResolucionRecord() {
        super(Resolucion.RESOLUCION);
    }

    /**
     * Create a detached, initialised ResolucionRecord
     */
    public ResolucionRecord(Integer idresolucion, String resolucion, Integer tktinicial, Integer tktfinal, Integer tktactual, Integer tktalerta, String serie, Date fecha, Integer idcaja, Boolean activa) {
        super(Resolucion.RESOLUCION);

        set(0, idresolucion);
        set(1, resolucion);
        set(2, tktinicial);
        set(3, tktfinal);
        set(4, tktactual);
        set(5, tktalerta);
        set(6, serie);
        set(7, fecha);
        set(8, idcaja);
        set(9, activa);
    }
}
