/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VAsociadoReceta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAsociadoRecetaRecord extends TableRecordImpl<VAsociadoRecetaRecord> implements Record4<Integer, String, Integer, String> {

    private static final long serialVersionUID = 314287861;

    /**
     * Setter for <code>public.v_asociado_receta.idreceta</code>.
     */
    public void setIdreceta(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_asociado_receta.idreceta</code>.
     */
    public Integer getIdreceta() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_asociado_receta.receta</code>.
     */
    public void setReceta(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_asociado_receta.receta</code>.
     */
    public String getReceta() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_asociado_receta.ingrediente</code>.
     */
    public void setIngrediente(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_asociado_receta.ingrediente</code>.
     */
    public Integer getIngrediente() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_asociado_receta.nombre</code>.
     */
    public void setNombre(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_asociado_receta.nombre</code>.
     */
    public String getNombre() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VAsociadoReceta.V_ASOCIADO_RECETA.IDRECETA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VAsociadoReceta.V_ASOCIADO_RECETA.RECETA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VAsociadoReceta.V_ASOCIADO_RECETA.INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VAsociadoReceta.V_ASOCIADO_RECETA.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdreceta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReceta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIngrediente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAsociadoRecetaRecord value1(Integer value) {
        setIdreceta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAsociadoRecetaRecord value2(String value) {
        setReceta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAsociadoRecetaRecord value3(Integer value) {
        setIngrediente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAsociadoRecetaRecord value4(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAsociadoRecetaRecord values(Integer value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAsociadoRecetaRecord
     */
    public VAsociadoRecetaRecord() {
        super(VAsociadoReceta.V_ASOCIADO_RECETA);
    }

    /**
     * Create a detached, initialised VAsociadoRecetaRecord
     */
    public VAsociadoRecetaRecord(Integer idreceta, String receta, Integer ingrediente, String nombre) {
        super(VAsociadoReceta.V_ASOCIADO_RECETA);

        set(0, idreceta);
        set(1, receta);
        set(2, ingrediente);
        set(3, nombre);
    }
}
