/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VIngredientes;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VIngredientesRecord extends TableRecordImpl<VIngredientesRecord> implements Record10<Integer, String, BigDecimal, Double, Double, Double, Integer, String, String, Boolean> {

    private static final long serialVersionUID = 275881086;

    /**
     * Setter for <code>public.v_ingredientes.idingrediente</code>.
     */
    public void setIdingrediente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.idingrediente</code>.
     */
    public Integer getIdingrediente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_ingredientes.ingrediente</code>.
     */
    public void setIngrediente(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.ingrediente</code>.
     */
    public String getIngrediente() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_ingredientes.costo</code>.
     */
    public void setCosto(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.costo</code>.
     */
    public BigDecimal getCosto() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.v_ingredientes.stock</code>.
     */
    public void setStock(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.stock</code>.
     */
    public Double getStock() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.v_ingredientes.maximo</code>.
     */
    public void setMaximo(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.maximo</code>.
     */
    public Double getMaximo() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.v_ingredientes.minimo</code>.
     */
    public void setMinimo(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.minimo</code>.
     */
    public Double getMinimo() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.v_ingredientes.idunidad</code>.
     */
    public void setIdunidad(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.idunidad</code>.
     */
    public Integer getIdunidad() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.v_ingredientes.unidad</code>.
     */
    public void setUnidad(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.unidad</code>.
     */
    public String getUnidad() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_ingredientes.tipo</code>.
     */
    public void setTipo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.tipo</code>.
     */
    public String getTipo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_ingredientes.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_ingredientes.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, BigDecimal, Double, Double, Double, Integer, String, String, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, BigDecimal, Double, Double, Double, Integer, String, String, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VIngredientes.V_INGREDIENTES.IDINGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VIngredientes.V_INGREDIENTES.INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return VIngredientes.V_INGREDIENTES.COSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return VIngredientes.V_INGREDIENTES.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VIngredientes.V_INGREDIENTES.MAXIMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VIngredientes.V_INGREDIENTES.MINIMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return VIngredientes.V_INGREDIENTES.IDUNIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VIngredientes.V_INGREDIENTES.UNIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VIngredientes.V_INGREDIENTES.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return VIngredientes.V_INGREDIENTES.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdingrediente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIngrediente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getMaximo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getMinimo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdunidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUnidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value1(Integer value) {
        setIdingrediente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value2(String value) {
        setIngrediente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value3(BigDecimal value) {
        setCosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value4(Double value) {
        setStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value5(Double value) {
        setMaximo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value6(Double value) {
        setMinimo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value7(Integer value) {
        setIdunidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value8(String value) {
        setUnidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value9(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord value10(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VIngredientesRecord values(Integer value1, String value2, BigDecimal value3, Double value4, Double value5, Double value6, Integer value7, String value8, String value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VIngredientesRecord
     */
    public VIngredientesRecord() {
        super(VIngredientes.V_INGREDIENTES);
    }

    /**
     * Create a detached, initialised VIngredientesRecord
     */
    public VIngredientesRecord(Integer idingrediente, String ingrediente, BigDecimal costo, Double stock, Double maximo, Double minimo, Integer idunidad, String unidad, String tipo, Boolean baja) {
        super(VIngredientes.V_INGREDIENTES);

        set(0, idingrediente);
        set(1, ingrediente);
        set(2, costo);
        set(3, stock);
        set(4, maximo);
        set(5, minimo);
        set(6, idunidad);
        set(7, unidad);
        set(8, tipo);
        set(9, baja);
    }
}
