/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VModHora;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VModHoraRecord extends TableRecordImpl<VModHoraRecord> implements Record1<BigDecimal> {

    private static final long serialVersionUID = -1590018827;

    /**
     * Setter for <code>public.v_mod_hora.mod</code>.
     */
    public void setMod(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_mod_hora.mod</code>.
     */
    public BigDecimal getMod() {
        return (BigDecimal) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<BigDecimal> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<BigDecimal> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return VModHora.V_MOD_HORA.MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VModHoraRecord value1(BigDecimal value) {
        setMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VModHoraRecord values(BigDecimal value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VModHoraRecord
     */
    public VModHoraRecord() {
        super(VModHora.V_MOD_HORA);
    }

    /**
     * Create a detached, initialised VModHoraRecord
     */
    public VModHoraRecord(BigDecimal mod) {
        super(VModHora.V_MOD_HORA);

        set(0, mod);
    }
}
