/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Cliente;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteRecord extends UpdatableRecordImpl<ClienteRecord> implements Record8<Integer, String, String, String, String, String, Boolean, String> {

    private static final long serialVersionUID = -954617622;

    /**
     * Setter for <code>public.cliente.idcliente</code>.
     */
    public void setIdcliente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cliente.idcliente</code>.
     */
    public Integer getIdcliente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.cliente.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cliente.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cliente.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cliente.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.cliente.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cliente.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.cliente.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cliente.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cliente.tipo</code>.
     */
    public void setTipo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cliente.tipo</code>.
     */
    public String getTipo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.cliente.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cliente.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.cliente.dui</code>.
     */
    public void setDui(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.cliente.dui</code>.
     */
    public String getDui() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, Boolean, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, Boolean, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cliente.CLIENTE.IDCLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cliente.CLIENTE.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Cliente.CLIENTE.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Cliente.CLIENTE.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Cliente.CLIENTE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Cliente.CLIENTE.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Cliente.CLIENTE.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Cliente.CLIENTE.DUI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDui();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value1(Integer value) {
        setIdcliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value6(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value7(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value8(String value) {
        setDui(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClienteRecord
     */
    public ClienteRecord() {
        super(Cliente.CLIENTE);
    }

    /**
     * Create a detached, initialised ClienteRecord
     */
    public ClienteRecord(Integer idcliente, String nombre, String direccion, String telefono, String email, String tipo, Boolean baja, String dui) {
        super(Cliente.CLIENTE);

        set(0, idcliente);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, email);
        set(5, tipo);
        set(6, baja);
        set(7, dui);
    }
}
