/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.DetalleVenta;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleVentaRecord extends TableRecordImpl<DetalleVentaRecord> implements Record7<Integer, Integer, Integer, BigDecimal, String, Boolean, Integer> {

    private static final long serialVersionUID = 1344344205;

    /**
     * Setter for <code>public.detalle_venta.idventa</code>.
     */
    public void setIdventa(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.detalle_venta.idventa</code>.
     */
    public Integer getIdventa() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.detalle_venta.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.detalle_venta.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.detalle_venta.cantidad</code>.
     */
    public void setCantidad(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.detalle_venta.cantidad</code>.
     */
    public Integer getCantidad() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.detalle_venta.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.detalle_venta.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.detalle_venta.tipo</code>.
     */
    public void setTipo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.detalle_venta.tipo</code>.
     */
    public String getTipo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.detalle_venta.espromo</code>.
     */
    public void setEspromo(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.detalle_venta.espromo</code>.
     */
    public Boolean getEspromo() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.detalle_venta.idpromocion</code>.
     */
    public void setIdpromocion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.detalle_venta.idpromocion</code>.
     */
    public Integer getIdpromocion() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, BigDecimal, String, Boolean, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, BigDecimal, String, Boolean, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DetalleVenta.DETALLE_VENTA.IDVENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DetalleVenta.DETALLE_VENTA.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DetalleVenta.DETALLE_VENTA.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return DetalleVenta.DETALLE_VENTA.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DetalleVenta.DETALLE_VENTA.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return DetalleVenta.DETALLE_VENTA.ESPROMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DetalleVenta.DETALLE_VENTA.IDPROMOCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdventa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getEspromo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdpromocion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value1(Integer value) {
        setIdventa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value2(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value3(Integer value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value4(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value5(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value6(Boolean value) {
        setEspromo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord value7(Integer value) {
        setIdpromocion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleVentaRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, String value5, Boolean value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DetalleVentaRecord
     */
    public DetalleVentaRecord() {
        super(DetalleVenta.DETALLE_VENTA);
    }

    /**
     * Create a detached, initialised DetalleVentaRecord
     */
    public DetalleVentaRecord(Integer idventa, Integer idproducto, Integer cantidad, BigDecimal precio, String tipo, Boolean espromo, Integer idpromocion) {
        super(DetalleVenta.DETALLE_VENTA);

        set(0, idventa);
        set(1, idproducto);
        set(2, cantidad);
        set(3, precio);
        set(4, tipo);
        set(5, espromo);
        set(6, idpromocion);
    }
}
