/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Modulo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuloRecord extends UpdatableRecordImpl<ModuloRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 236154502;

    /**
     * Setter for <code>public.modulo.idmodulo</code>.
     */
    public void setIdmodulo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.modulo.idmodulo</code>.
     */
    public Integer getIdmodulo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.modulo.modulo</code>.
     */
    public void setModulo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.modulo.modulo</code>.
     */
    public String getModulo() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Modulo.MODULO.IDMODULO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Modulo.MODULO.MODULO_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdmodulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getModulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModuloRecord value1(Integer value) {
        setIdmodulo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModuloRecord value2(String value) {
        setModulo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModuloRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuloRecord
     */
    public ModuloRecord() {
        super(Modulo.MODULO);
    }

    /**
     * Create a detached, initialised ModuloRecord
     */
    public ModuloRecord(Integer idmodulo, String modulo) {
        super(Modulo.MODULO);

        set(0, idmodulo);
        set(1, modulo);
    }
}
