/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.Producto;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductoRecord extends UpdatableRecordImpl<ProductoRecord> implements Record14<Integer, String, String, Integer, byte[], Boolean, String, String, BigDecimal, Integer, Integer, Integer, Double, Double> {

    private static final long serialVersionUID = 986673246;

    /**
     * Setter for <code>public.producto.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.producto.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.producto.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.producto.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.producto.detalle</code>.
     */
    public void setDetalle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.producto.detalle</code>.
     */
    public String getDetalle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.producto.idcategoria</code>.
     */
    public void setIdcategoria(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.producto.idcategoria</code>.
     */
    public Integer getIdcategoria() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.producto.imagen</code>.
     */
    public void setImagen(byte[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.producto.imagen</code>.
     */
    public byte[] getImagen() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>public.producto.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.producto.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.producto.tipo</code>.
     */
    public void setTipo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.producto.tipo</code>.
     */
    public String getTipo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.producto.tipoventa</code>.
     */
    public void setTipoventa(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.producto.tipoventa</code>.
     */
    public String getTipoventa() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.producto.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.producto.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.producto.idreceta</code>.
     */
    public void setIdreceta(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.producto.idreceta</code>.
     */
    public Integer getIdreceta() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.producto.idinsumo</code>.
     */
    public void setIdinsumo(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.producto.idinsumo</code>.
     */
    public Integer getIdinsumo() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.producto.porciones</code>.
     */
    public void setPorciones(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.producto.porciones</code>.
     */
    public Integer getPorciones() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.producto.descuento</code>.
     */
    public void setDescuento(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.producto.descuento</code>.
     */
    public Double getDescuento() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.producto.stock</code>.
     */
    public void setStock(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.producto.stock</code>.
     */
    public Double getStock() {
        return (Double) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, Integer, byte[], Boolean, String, String, BigDecimal, Integer, Integer, Integer, Double, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, Integer, byte[], Boolean, String, String, BigDecimal, Integer, Integer, Integer, Double, Double> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Producto.PRODUCTO.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Producto.PRODUCTO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Producto.PRODUCTO.DETALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Producto.PRODUCTO.IDCATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field5() {
        return Producto.PRODUCTO.IMAGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Producto.PRODUCTO.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Producto.PRODUCTO.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Producto.PRODUCTO.TIPOVENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Producto.PRODUCTO.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Producto.PRODUCTO.IDRECETA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Producto.PRODUCTO.IDINSUMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Producto.PRODUCTO.PORCIONES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return Producto.PRODUCTO.DESCUENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field14() {
        return Producto.PRODUCTO.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value5() {
        return getImagen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTipoventa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIdreceta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getIdinsumo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getPorciones();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value14() {
        return getStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value1(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value3(String value) {
        setDetalle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value4(Integer value) {
        setIdcategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value5(byte[] value) {
        setImagen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value6(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value7(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value8(String value) {
        setTipoventa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value9(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value10(Integer value) {
        setIdreceta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value11(Integer value) {
        setIdinsumo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value12(Integer value) {
        setPorciones(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value13(Double value) {
        setDescuento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value14(Double value) {
        setStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord values(Integer value1, String value2, String value3, Integer value4, byte[] value5, Boolean value6, String value7, String value8, BigDecimal value9, Integer value10, Integer value11, Integer value12, Double value13, Double value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductoRecord
     */
    public ProductoRecord() {
        super(Producto.PRODUCTO);
    }

    /**
     * Create a detached, initialised ProductoRecord
     */
    public ProductoRecord(Integer idproducto, String nombre, String detalle, Integer idcategoria, byte[] imagen, Boolean baja, String tipo, String tipoventa, BigDecimal precio, Integer idreceta, Integer idinsumo, Integer porciones, Double descuento, Double stock) {
        super(Producto.PRODUCTO);

        set(0, idproducto);
        set(1, nombre);
        set(2, detalle);
        set(3, idcategoria);
        set(4, imagen);
        set(5, baja);
        set(6, tipo);
        set(7, tipoventa);
        set(8, precio);
        set(9, idreceta);
        set(10, idinsumo);
        set(11, porciones);
        set(12, descuento);
        set(13, stock);
    }
}
