/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VDetalleCotizacion;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDetalleCotizacionRecord extends TableRecordImpl<VDetalleCotizacionRecord> implements Record8<Integer, String, Integer, String, Integer, BigDecimal, BigDecimal, String> {

    private static final long serialVersionUID = -690897405;

    /**
     * Setter for <code>public.v_detalle_cotizacion.idcotizacion</code>.
     */
    public void setIdcotizacion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.idcotizacion</code>.
     */
    public Integer getIdcotizacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.numero</code>.
     */
    public void setNumero(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.numero</code>.
     */
    public String getNumero() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.nombre</code>.
     */
    public void setNombre(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.nombre</code>.
     */
    public String getNombre() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.cantidad</code>.
     */
    public void setCantidad(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.cantidad</code>.
     */
    public Integer getCantidad() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.subtotal</code>.
     */
    public void setSubtotal(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.subtotal</code>.
     */
    public BigDecimal getSubtotal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.tipo</code>.
     */
    public void setTipo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.tipo</code>.
     */
    public String getTipo() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, String, Integer, BigDecimal, BigDecimal, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, String, Integer, BigDecimal, BigDecimal, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.IDCOTIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.NUMERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.SUBTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcotizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value1(Integer value) {
        setIdcotizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value2(String value) {
        setNumero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value3(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value4(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value5(Integer value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value6(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value7(BigDecimal value) {
        setSubtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value8(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5, BigDecimal value6, BigDecimal value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VDetalleCotizacionRecord
     */
    public VDetalleCotizacionRecord() {
        super(VDetalleCotizacion.V_DETALLE_COTIZACION);
    }

    /**
     * Create a detached, initialised VDetalleCotizacionRecord
     */
    public VDetalleCotizacionRecord(Integer idcotizacion, String numero, Integer idproducto, String nombre, Integer cantidad, BigDecimal precio, BigDecimal subtotal, String tipo) {
        super(VDetalleCotizacion.V_DETALLE_COTIZACION);

        set(0, idcotizacion);
        set(1, numero);
        set(2, idproducto);
        set(3, nombre);
        set(4, cantidad);
        set(5, precio);
        set(6, subtotal);
        set(7, tipo);
    }
}
