/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VEmpleados;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VEmpleadosRecord extends TableRecordImpl<VEmpleadosRecord> implements Record14<Integer, String, String, String, String, String, String, Integer, String, BigDecimal, Integer, BigDecimal, Boolean, Boolean> {

    private static final long serialVersionUID = -1448218119;

    /**
     * Setter for <code>public.v_empleados.idempleado</code>.
     */
    public void setIdempleado(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_empleados.idempleado</code>.
     */
    public Integer getIdempleado() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_empleados.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_empleados.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_empleados.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_empleados.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_empleados.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_empleados.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_empleados.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_empleados.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_empleados.dui</code>.
     */
    public void setDui(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_empleados.dui</code>.
     */
    public String getDui() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_empleados.nit</code>.
     */
    public void setNit(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_empleados.nit</code>.
     */
    public String getNit() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_empleados.idpuesto</code>.
     */
    public void setIdpuesto(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_empleados.idpuesto</code>.
     */
    public Integer getIdpuesto() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.v_empleados.puesto</code>.
     */
    public void setPuesto(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_empleados.puesto</code>.
     */
    public String getPuesto() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_empleados.salariodia</code>.
     */
    public void setSalariodia(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_empleados.salariodia</code>.
     */
    public BigDecimal getSalariodia() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.v_empleados.diaslaborales</code>.
     */
    public void setDiaslaborales(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_empleados.diaslaborales</code>.
     */
    public Integer getDiaslaborales() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.v_empleados.salario_mensual</code>.
     */
    public void setSalarioMensual(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_empleados.salario_mensual</code>.
     */
    public BigDecimal getSalarioMensual() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.v_empleados.manodeobra</code>.
     */
    public void setManodeobra(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_empleados.manodeobra</code>.
     */
    public Boolean getManodeobra() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.v_empleados.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_empleados.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, String, String, Integer, String, BigDecimal, Integer, BigDecimal, Boolean, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, String, String, Integer, String, BigDecimal, Integer, BigDecimal, Boolean, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VEmpleados.V_EMPLEADOS.IDEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VEmpleados.V_EMPLEADOS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VEmpleados.V_EMPLEADOS.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VEmpleados.V_EMPLEADOS.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VEmpleados.V_EMPLEADOS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VEmpleados.V_EMPLEADOS.DUI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VEmpleados.V_EMPLEADOS.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VEmpleados.V_EMPLEADOS.IDPUESTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VEmpleados.V_EMPLEADOS.PUESTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return VEmpleados.V_EMPLEADOS.SALARIODIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return VEmpleados.V_EMPLEADOS.DIASLABORALES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return VEmpleados.V_EMPLEADOS.SALARIO_MENSUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return VEmpleados.V_EMPLEADOS.MANODEOBRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return VEmpleados.V_EMPLEADOS.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDui();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdpuesto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPuesto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getSalariodia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getDiaslaborales();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getSalarioMensual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getManodeobra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value1(Integer value) {
        setIdempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value6(String value) {
        setDui(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value7(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value8(Integer value) {
        setIdpuesto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value9(String value) {
        setPuesto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value10(BigDecimal value) {
        setSalariodia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value11(Integer value) {
        setDiaslaborales(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value12(BigDecimal value) {
        setSalarioMensual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value13(Boolean value) {
        setManodeobra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord value14(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VEmpleadosRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, BigDecimal value10, Integer value11, BigDecimal value12, Boolean value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VEmpleadosRecord
     */
    public VEmpleadosRecord() {
        super(VEmpleados.V_EMPLEADOS);
    }

    /**
     * Create a detached, initialised VEmpleadosRecord
     */
    public VEmpleadosRecord(Integer idempleado, String nombre, String direccion, String telefono, String email, String dui, String nit, Integer idpuesto, String puesto, BigDecimal salariodia, Integer diaslaborales, BigDecimal salarioMensual, Boolean manodeobra, Boolean baja) {
        super(VEmpleados.V_EMPLEADOS);

        set(0, idempleado);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, email);
        set(5, dui);
        set(6, nit);
        set(7, idpuesto);
        set(8, puesto);
        set(9, salariodia);
        set(10, diaslaborales);
        set(11, salarioMensual);
        set(12, manodeobra);
        set(13, baja);
    }
}
