/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VInsumos;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VInsumosRecord extends TableRecordImpl<VInsumosRecord> implements Record10<Integer, String, BigDecimal, Double, Double, Double, String, String, Boolean, Boolean> {

    private static final long serialVersionUID = 1159499080;

    /**
     * Setter for <code>public.v_insumos.idinsumo</code>.
     */
    public void setIdinsumo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_insumos.idinsumo</code>.
     */
    public Integer getIdinsumo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_insumos.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_insumos.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_insumos.costo</code>.
     */
    public void setCosto(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_insumos.costo</code>.
     */
    public BigDecimal getCosto() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.v_insumos.minimo</code>.
     */
    public void setMinimo(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_insumos.minimo</code>.
     */
    public Double getMinimo() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.v_insumos.maximo</code>.
     */
    public void setMaximo(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_insumos.maximo</code>.
     */
    public Double getMaximo() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.v_insumos.stock</code>.
     */
    public void setStock(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_insumos.stock</code>.
     */
    public Double getStock() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.v_insumos.unidad</code>.
     */
    public void setUnidad(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_insumos.unidad</code>.
     */
    public String getUnidad() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_insumos.medida</code>.
     */
    public void setMedida(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_insumos.medida</code>.
     */
    public String getMedida() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_insumos.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_insumos.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.v_insumos.produccion</code>.
     */
    public void setProduccion(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_insumos.produccion</code>.
     */
    public Boolean getProduccion() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, BigDecimal, Double, Double, Double, String, String, Boolean, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, BigDecimal, Double, Double, Double, String, String, Boolean, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VInsumos.V_INSUMOS.IDINSUMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VInsumos.V_INSUMOS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return VInsumos.V_INSUMOS.COSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return VInsumos.V_INSUMOS.MINIMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VInsumos.V_INSUMOS.MAXIMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VInsumos.V_INSUMOS.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VInsumos.V_INSUMOS.UNIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VInsumos.V_INSUMOS.MEDIDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return VInsumos.V_INSUMOS.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return VInsumos.V_INSUMOS.PRODUCCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdinsumo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getMinimo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getMaximo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUnidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMedida();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getProduccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value1(Integer value) {
        setIdinsumo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value3(BigDecimal value) {
        setCosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value4(Double value) {
        setMinimo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value5(Double value) {
        setMaximo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value6(Double value) {
        setStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value7(String value) {
        setUnidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value8(String value) {
        setMedida(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value9(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord value10(Boolean value) {
        setProduccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VInsumosRecord values(Integer value1, String value2, BigDecimal value3, Double value4, Double value5, Double value6, String value7, String value8, Boolean value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VInsumosRecord
     */
    public VInsumosRecord() {
        super(VInsumos.V_INSUMOS);
    }

    /**
     * Create a detached, initialised VInsumosRecord
     */
    public VInsumosRecord(Integer idinsumo, String nombre, BigDecimal costo, Double minimo, Double maximo, Double stock, String unidad, String medida, Boolean baja, Boolean produccion) {
        super(VInsumos.V_INSUMOS);

        set(0, idinsumo);
        set(1, nombre);
        set(2, costo);
        set(3, minimo);
        set(4, maximo);
        set(5, stock);
        set(6, unidad);
        set(7, medida);
        set(8, baja);
        set(9, produccion);
    }
}
