/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables.records;


import com.pereira.manolos.datos.database.tables.VProductos;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VProductosRecord extends TableRecordImpl<VProductosRecord> implements Record14<Integer, String, String, byte[], Integer, Double, BigDecimal, String, Double, Integer, Integer, BigDecimal, String, Boolean> {

    private static final long serialVersionUID = 927497602;

    /**
     * Setter for <code>public.v_productos.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_productos.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_productos.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_productos.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_productos.detalle</code>.
     */
    public void setDetalle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_productos.detalle</code>.
     */
    public String getDetalle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_productos.imagen</code>.
     */
    public void setImagen(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_productos.imagen</code>.
     */
    public byte[] getImagen() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.v_productos.porciones</code>.
     */
    public void setPorciones(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_productos.porciones</code>.
     */
    public Integer getPorciones() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_productos.descuento</code>.
     */
    public void setDescuento(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_productos.descuento</code>.
     */
    public Double getDescuento() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.v_productos.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_productos.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.v_productos.tipo</code>.
     */
    public void setTipo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_productos.tipo</code>.
     */
    public String getTipo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_productos.stock</code>.
     */
    public void setStock(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_productos.stock</code>.
     */
    public Double getStock() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.v_productos.horas</code>.
     */
    public void setHoras(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_productos.horas</code>.
     */
    public Integer getHoras() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.v_productos.minutos</code>.
     */
    public void setMinutos(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_productos.minutos</code>.
     */
    public Integer getMinutos() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.v_productos.costo</code>.
     */
    public void setCosto(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_productos.costo</code>.
     */
    public BigDecimal getCosto() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.v_productos.categoria</code>.
     */
    public void setCategoria(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_productos.categoria</code>.
     */
    public String getCategoria() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_productos.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_productos.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, byte[], Integer, Double, BigDecimal, String, Double, Integer, Integer, BigDecimal, String, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, byte[], Integer, Double, BigDecimal, String, Double, Integer, Integer, BigDecimal, String, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VProductos.V_PRODUCTOS.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VProductos.V_PRODUCTOS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VProductos.V_PRODUCTOS.DETALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return VProductos.V_PRODUCTOS.IMAGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return VProductos.V_PRODUCTOS.PORCIONES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VProductos.V_PRODUCTOS.DESCUENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return VProductos.V_PRODUCTOS.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VProductos.V_PRODUCTOS.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return VProductos.V_PRODUCTOS.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return VProductos.V_PRODUCTOS.HORAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return VProductos.V_PRODUCTOS.MINUTOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return VProductos.V_PRODUCTOS.COSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VProductos.V_PRODUCTOS.CATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return VProductos.V_PRODUCTOS.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getImagen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPorciones();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getHoras();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getMinutos();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value1(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value3(String value) {
        setDetalle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value4(byte[] value) {
        setImagen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value5(Integer value) {
        setPorciones(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value6(Double value) {
        setDescuento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value7(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value8(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value9(Double value) {
        setStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value10(Integer value) {
        setHoras(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value11(Integer value) {
        setMinutos(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value12(BigDecimal value) {
        setCosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value13(String value) {
        setCategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord value14(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductosRecord values(Integer value1, String value2, String value3, byte[] value4, Integer value5, Double value6, BigDecimal value7, String value8, Double value9, Integer value10, Integer value11, BigDecimal value12, String value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VProductosRecord
     */
    public VProductosRecord() {
        super(VProductos.V_PRODUCTOS);
    }

    /**
     * Create a detached, initialised VProductosRecord
     */
    public VProductosRecord(Integer idproducto, String nombre, String detalle, byte[] imagen, Integer porciones, Double descuento, BigDecimal precio, String tipo, Double stock, Integer horas, Integer minutos, BigDecimal costo, String categoria, Boolean baja) {
        super(VProductos.V_PRODUCTOS);

        set(0, idproducto);
        set(1, nombre);
        set(2, detalle);
        set(3, imagen);
        set(4, porciones);
        set(5, descuento);
        set(6, precio);
        set(7, tipo);
        set(8, stock);
        set(9, horas);
        set(10, minutos);
        set(11, costo);
        set(12, categoria);
        set(13, baja);
    }
}
