/**
 * This class is generated by jOOQ
 */
package com.pereira.manolos.datos.database.tables;


import com.pereira.manolos.datos.database.Keys;
import com.pereira.manolos.datos.database.Public;
import com.pereira.manolos.datos.database.tables.records.CategoriaProductoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriaProducto extends TableImpl<CategoriaProductoRecord> {

    private static final long serialVersionUID = -533379784;

    /**
     * The reference instance of <code>public.categoria_producto</code>
     */
    public static final CategoriaProducto CATEGORIA_PRODUCTO = new CategoriaProducto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoriaProductoRecord> getRecordType() {
        return CategoriaProductoRecord.class;
    }

    /**
     * The column <code>public.categoria_producto.idcategoria</code>.
     */
    public final TableField<CategoriaProductoRecord, Integer> IDCATEGORIA = createField("idcategoria", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('categoria_producto_idcategoria_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.categoria_producto.nombre</code>.
     */
    public final TableField<CategoriaProductoRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.categoria_producto.imagen</code>.
     */
    public final TableField<CategoriaProductoRecord, byte[]> IMAGEN = createField("imagen", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>public.categoria_producto</code> table reference
     */
    public CategoriaProducto() {
        this("categoria_producto", null);
    }

    /**
     * Create an aliased <code>public.categoria_producto</code> table reference
     */
    public CategoriaProducto(String alias) {
        this(alias, CATEGORIA_PRODUCTO);
    }

    private CategoriaProducto(String alias, Table<CategoriaProductoRecord> aliased) {
        this(alias, aliased, null);
    }

    private CategoriaProducto(String alias, Table<CategoriaProductoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CategoriaProductoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CATEGORIA_PRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CategoriaProductoRecord> getPrimaryKey() {
        return Keys.CATEGORIA_PRODUCTO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CategoriaProductoRecord>> getKeys() {
        return Arrays.<UniqueKey<CategoriaProductoRecord>>asList(Keys.CATEGORIA_PRODUCTO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaProducto as(String alias) {
        return new CategoriaProducto(alias, this);
    }

    /**
     * Rename this table
     */
    public CategoriaProducto rename(String name) {
        return new CategoriaProducto(name, null);
    }
}
